"""Copy the run that FINDINGS.md quotes into `evidence/`, which IS committed.

`results/` and `.work/` are scratch — re-running overwrites them. The numbers in
FINDINGS.md have to survive that, or the next reader is asked to trust a
document with nothing behind it.

The 5.8 MB ingest trace is deliberately left out: it is 18,297 statements of
real crawl data, it is regenerated by `baseline.py` in under a second, and it
does not belong in the repository. The query trace (24 KB) IS carried, because
it is the evidence that the browser replayed the Data page's real SQL rather
than something that resembles it.
"""
from __future__ import annotations

import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
EVIDENCE = HERE / "evidence"

COPIES = [
    (".work/snapshot-facts.json", "snapshot-facts.json"),
    (".work/trace-queries.json", "trace-queries.json"),
    (".work/baseline-1.json", "baseline-run1.json"),
    (".work/baseline-2.json", "baseline-run2.json"),
    (".work/baseline-3.json", "baseline-run3.json"),
    ("results/main.json", "browser-capacity-durability.json"),
    ("results/migrate.json", "browser-migrate-accesshandlepool.json"),
    ("results/speed.json", "browser-speed-three-engines.json"),
    ("results/speed-fast.json", "browser-speed-fast-engines.json"),
    ("results/sw.json", "browser-service-worker.json"),
    ("results/no-unlimited.json", "browser-without-unlimitedstorage.json"),
]


def main() -> int:
    EVIDENCE.mkdir(exist_ok=True)
    missing = []
    for src, dst in COPIES:
        source = HERE / src
        if not source.exists():
            missing.append(src)
            continue
        shutil.copy2(source, EVIDENCE / dst)
        print(f"{src:44s} -> evidence/{dst}")
    if missing:
        print("\nnot found (re-run the phase that produces it):")
        for m in missing:
            print(f"  {m}")
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
