"""Every `var(--x)` without a fallback names a property something actually sets.

THIS GUARD WAS CITED BEFORE IT EXISTED. `docs/LESSONS.md` named
`test_every_custom_property_a_stylesheet_reads_is_one_something_defines` as the
thing protecting a paragraph about state colours, and a grep for that name
returned the citation and nothing else. Measured 2026-08-29 while reviewing the
design system against Supabase's: **twelve declarations across four files read a
custom property nothing declared**, including the one the citing paragraph was
about. The citation was covering the exact defect it named.

WHY NOTHING CAUGHT IT, and the seam is worth keeping. `tests/test_the_tests_name_tests_that_exist.py`
guards backticked test names -- but it reads only `tests/*.py`, so a name written
in a document is outside it. `tests/test_the_documents_cite_what_they_claim.py`
reads `docs/` -- but it checks `file:line` citations, and a bare backticked test
name has no line. A test name inside a document falls between the two.

WHAT AN UNDECLARED READ COSTS, and it is never an error. An invalid `var()` makes
the WHOLE declaration invalid at computed-value time, then the property falls back
to its inherited or initial value. So:

  * `top: calc(var(--sticky-tabs) + var(--sp-4))` -> `top: auto`. Two sidebars
    marked `position: sticky` never stuck, for a month, on the two pages where a
    long form most needs one.
  * `background: var(--control-active)` -> `unset`, which is transparent. A pressed
    split-button option showed the container behind it while only its border moved.
  * `color: var(--fg)` -> inherited, and the base rule was `color: inherit`. The
    hover changed nothing at all.
  * `border-inline-start-color: var(--green)` -> not inherited, so a completed build
    step simply lost its colour.

Nothing throws. Nothing looks broken in a screenshot. A reviewer reading the CSS
sees a plausible token name.

WHAT COUNTS AS "SOMETHING DEFINES IT". A property may be declared in any authored
stylesheet, set from JavaScript with `setProperty`, or written as an inline style
in a template. All three are real and all three are how this repository already
works -- `design/appearance.js` writes 36 of them from JS, and the tonal blocks
declare others only under a `[data-color-mode]` selector. A read with a FALLBACK
(`var(--x, 1rem)`) is deliberate and is not checked: the author said what happens
when it is missing.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

#: This walks `extension/*.css` — two of the four defects it was written for were
#: there — so without the mark it would stop running on an extension-only change,
#: which is exactly the change most likely to introduce a fifth.
pytestmark = pytest.mark.extension

ROOT = Path(__file__).resolve().parent.parent

#: The stylesheets a human writes. The four generated byte copies are excluded by
#: name -- including them would let a copy satisfy the guard for its source, and
#: every census in this repository that forgot has triple-counted.
GENERATED = {
    "extension/tokens.css",
    "extension/components.css",
    "scrapex/webui/static/tokens.css",
    "scrapex/webui/static/components.css",
}

#: A read without a fallback: `var(--name)` with nothing after the name but `)`.
#: A comma means a fallback was supplied and the author owns the outcome.
READ = re.compile(r"var\(\s*(--[A-Za-z0-9-]+)\s*\)")
#: A declaration, anywhere in any block.
DECLARE = re.compile(r"(--[A-Za-z0-9-]+)\s*:")
#: Set from script, or written inline into markup.
FROM_SCRIPT = re.compile(r"""setProperty\(\s*['"`](--[A-Za-z0-9-]+)""")
FROM_MARKUP = re.compile(r"""style\s*=\s*["'][^"']*?(--[A-Za-z0-9-]+)\s*:""")
COMMENT = re.compile(r"/\*.*?\*/", re.S)


def _authored_stylesheets() -> list[Path]:
    sheets = []
    for path in sorted(ROOT.glob("design/*.css")) + \
            sorted(ROOT.glob("extension/*.css")) + \
            sorted(ROOT.glob("scrapex/webui/static/*.css")) + \
            sorted(ROOT.glob("scrapex/webui/static/pages/*.css")):
        relative = path.relative_to(ROOT).as_posix()
        if relative in GENERATED or "/vendor/" in relative:
            continue
        sheets.append(path)
    return sheets


def _defined_names() -> set[str]:
    names: set[str] = set()
    for sheet in _authored_stylesheets():
        names |= set(DECLARE.findall(COMMENT.sub("", sheet.read_text(encoding="utf-8"))))
    for pattern, globs in (
        (FROM_SCRIPT, ("design/*.js", "extension/*.js",
                       "scrapex/webui/static/*.js", "scrapex/webui/static/pages/*.js")),
        (FROM_MARKUP, ("extension/*.html", "scrapex/webui/templates/*.html",
                       "scrapex/webui/templates/**/*.html", "design/*.html")),
    ):
        for glob in globs:
            for path in sorted(ROOT.glob(glob)):
                if "/vendor/" in path.relative_to(ROOT).as_posix():
                    continue
                names |= set(pattern.findall(path.read_text(encoding="utf-8")))
    return names


@pytest.mark.parametrize(
    "sheet", _authored_stylesheets(),
    ids=[path.relative_to(ROOT).as_posix() for path in _authored_stylesheets()])
def test_every_custom_property_a_stylesheet_reads_is_one_something_defines(sheet):
    defined = _defined_names()
    text = COMMENT.sub("", sheet.read_text(encoding="utf-8"))

    missing = []
    for line_number, line in enumerate(text.split("\n"), 1):
        for name in READ.findall(line):
            if name not in defined:
                missing.append(f"{sheet.relative_to(ROOT).as_posix()}:{line_number} "
                               f"reads {name}, which nothing declares")

    assert not missing, (
        "an invalid var() makes the WHOLE declaration invalid and nothing throws:\n  "
        + "\n  ".join(missing)
        + "\nDeclare it, spell an existing role instead, or give the read a "
          "fallback and own what happens when it is absent.")


def test_the_guard_reads_the_sheets_it_claims_to():
    """A guard that walks an empty list is decoration, and this one is parametrized
    over a glob -- so a moved directory would silently pass every case by having
    no cases at all."""
    sheets = _authored_stylesheets()
    assert len(sheets) >= 18, f"only found {len(sheets)} authored stylesheets: {sheets}"
    names = {path.name for path in sheets}
    assert {"tokens.css", "components.css", "app.css", "webui.css"} <= names, names
    assert not (GENERATED & {p.relative_to(ROOT).as_posix() for p in sheets})


def test_a_fallback_is_not_reported():
    """The rule is about SILENT failure. `var(--x, 1rem)` is a stated decision, and
    reporting it would push authors toward declaring tokens they do not want."""
    assert READ.findall("top: var(--sticky-tabs)") == ["--sticky-tabs"]
    assert READ.findall("top: var(--sticky-tabs, 4rem)") == []
    assert READ.findall("top: calc(var(--a) + var(--b))") == ["--a", "--b"]
