-- ScrapeX-Engine, one database, one schema.
--
-- GENERATED by tools/squash_engine_baseline.py from the migration chain it
-- replaces: 16 numbered migrations collapsed into this file at
-- schema version 17. Do not hand-edit --
-- tests/test_the_squashed_baseline_carries_the_chain.py holds it against a
-- frozen record of everything that chain produced.
--
-- 67 tables, 79 indexes, 31 triggers, 2 views.
--
-- R-84: the base may be collapsed BEFORE publication and never after it.
-- Once a release marker exists, every migration is kept forever, because it
-- is not determined which version any user stopped at.

-- WHAT A FILE IS, before anything reads a table out of it. The application
-- id lives in the SQLite header, so a backup restored into the wrong place is
-- refused rather than half-used. Written from scrapex/database_ids.py, so the
-- two cannot drift apart.
PRAGMA foreign_keys = ON;
PRAGMA application_id = 1398293838;  -- 0x5358454E

-- ---- tables ------------------------------------------------------------------

CREATE TABLE absence_period (
    absence_period_id  INTEGER PRIMARY KEY,
    offer_id           INTEGER NOT NULL REFERENCES source_offer(offer_id),
    missing_since      TEXT NOT NULL,
    returned_at        TEXT,
    -- The run that established the absence, so the claim is auditable.
    detected_by_run_id INTEGER REFERENCES crawl_run(run_id)
);

CREATE TABLE attribute_definition (
    attribute_id        INTEGER PRIMARY KEY,
    attribute_code      TEXT NOT NULL UNIQUE,  -- 'length'
    name_ar             TEXT,                  -- 'الطول'
    name             TEXT,
    data_type           TEXT NOT NULL DEFAULT 'text' CHECK (data_type IN ('number','text','bool','date')),
    canonical_unit_id   INTEGER REFERENCES selling_unit(selling_unit_id),
    is_variant_defining INTEGER NOT NULL DEFAULT 0 CHECK (is_variant_defining IN (0,1)),
    is_matching_key     INTEGER NOT NULL DEFAULT 0 CHECK (is_matching_key IN (0,1))
);

CREATE TABLE brand (
    brand_id     INTEGER PRIMARY KEY,
    brand_name   TEXT NOT NULL UNIQUE,
    brand_name_ar TEXT,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE change_event (
    change_event_id   INTEGER PRIMARY KEY,
    source_product_id INTEGER REFERENCES source_product(source_product_id),
    source_variant_id INTEGER REFERENCES source_variant(source_variant_id),
    offer_id          INTEGER REFERENCES source_offer(offer_id),
    field_key         TEXT NOT NULL,        -- 'effective_price' | 'source_name' | 'availability' | ...
    previous_value    TEXT,                 -- NULL for a 'new' event
    new_value         TEXT,
    change_type       TEXT NOT NULL CHECK (change_type IN (
                          'new','field_updated','price_increase','price_decrease',
                          'unavailable','returned','removed')),
    detected_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    run_id            INTEGER REFERENCES crawl_run(run_id),
    job_id            INTEGER REFERENCES crawl_job(job_id)
);

CREATE TABLE classification_mapping (
    classification_mapping_id INTEGER PRIMARY KEY,
    source_node_id INTEGER NOT NULL REFERENCES classification_node(node_id),
    target_node_id INTEGER NOT NULL REFERENCES classification_node(node_id),
    confidence     REAL NOT NULL DEFAULT 1.0,
    mapping_method TEXT NOT NULL DEFAULT 'manual' CHECK (mapping_method IN ('manual','rule','ai')),
    review_status  TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending','approved','ignored')),
    valid_from     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to       TEXT
);

CREATE TABLE classification_node (
    node_id        INTEGER PRIMARY KEY,
    scheme_id      INTEGER NOT NULL REFERENCES classification_scheme(scheme_id),
    parent_node_id INTEGER REFERENCES classification_node(node_id),
    external_id    TEXT,                     -- site category id (madar uid, salla c-id)
    node_code      TEXT,
    node_name_ar      TEXT NOT NULL,
    category_url   TEXT,
    level          INTEGER NOT NULL DEFAULT 1
, node_name TEXT);

CREATE TABLE crawl_run (
    run_id              INTEGER PRIMARY KEY,
    source_id           INTEGER NOT NULL REFERENCES source_site(source_id),
    started_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    finished_at         TEXT,
    status              TEXT NOT NULL DEFAULT 'running'
        CHECK (status IN ('running','success','partial','failed')),
    products_discovered INTEGER NOT NULL DEFAULT 0,
    variants_discovered INTEGER NOT NULL DEFAULT 0,
    errors_count        INTEGER NOT NULL DEFAULT 0,
    requests_count      INTEGER NOT NULL DEFAULT 0,    -- F5 politeness accounting
    durations_json      TEXT,                          -- F7 per-phase wall-times
    extractor_version   TEXT
, job_id INTEGER REFERENCES crawl_job(job_id), rows_seen INTEGER NOT NULL DEFAULT 0, warning_count INTEGER NOT NULL DEFAULT 0, first_warning TEXT NOT NULL DEFAULT '');

CREATE TABLE "currency_rate" (
    currency_rate_id INTEGER PRIMARY KEY,
    currency         TEXT NOT NULL,            -- ISO code: EGP, SAR, EUR...
    per_usd          REAL NOT NULL CHECK (per_usd > 0),   -- 1 USD = per_usd currency
    as_of            TEXT NOT NULL,            -- the date the rate speaks for
    source_key       TEXT NOT NULL,            -- who published it
    -- WHAT KIND of publisher that is. 'provider' is a rate service whose
    -- business IS the rate; 'shop' is a storefront we read an implied rate off
    -- its own printed prices. A shop's rate is evidence about that shop, and
    -- must never be mistaken for a market rate.
    source_kind      TEXT NOT NULL CHECK (source_kind IN ('provider', 'shop')),
    recorded_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),

    UNIQUE (currency, as_of, source_key)
);

CREATE TABLE database_migration (
    migration_number INTEGER PRIMARY KEY,
    migration_name   TEXT NOT NULL,
    sha256            TEXT NOT NULL,
    applied_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE dataset_field (
    dataset_field_id INTEGER PRIMARY KEY,
    source_key       TEXT NOT NULL,          -- the dataset this column belongs to
    field_key        TEXT NOT NULL,          -- IMMUTABLE identity
    original_name    TEXT NOT NULL,          -- as first discovered; never rewritten
    display_name     TEXT,                   -- NULL = show original_name
    data_type        TEXT NOT NULL DEFAULT 'text'
        CHECK (data_type IN ('text','number','bool','date')),
    is_hidden        INTEGER NOT NULL DEFAULT 0 CHECK (is_hidden IN (0,1)),
    display_order    INTEGER NOT NULL DEFAULT 0,
    first_seen_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
, arranged_at TEXT);

CREATE TABLE feed_assignment (
    feed_assignment_id INTEGER PRIMARY KEY,
    material_id        INTEGER NOT NULL REFERENCES material(material_id),
    variant_id         INTEGER REFERENCES material_variant(variant_id),  -- NULL = all variants
    region             TEXT NOT NULL DEFAULT '*',
    source_id          INTEGER NOT NULL REFERENCES source_site(source_id),
    priority           INTEGER NOT NULL DEFAULT 1,       -- 1 = designated feeder; 2+ = declared fallbacks
    freshness_days     INTEGER NOT NULL,                 -- max age before this feeder counts stale
    review_status      TEXT NOT NULL DEFAULT 'approved'
        CHECK (review_status IN ('approved','pending','retired')),
    valid_from         TEXT NOT NULL DEFAULT (date('now')),
    valid_to           TEXT,                             -- temporal history; never DELETE
    notes              TEXT
);

CREATE TABLE field_definition (
    field_definition_id   INTEGER PRIMARY KEY,
    dataset_definition_id INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    field_key             TEXT NOT NULL,
    original_name         TEXT NOT NULL,
    display_name          TEXT,
    data_type             TEXT NOT NULL DEFAULT 'unknown'
        CHECK (data_type IN (
            'text','integer','decimal','boolean','date','datetime','url','json','unknown')),
    is_nullable           INTEGER NOT NULL DEFAULT 1 CHECK (is_nullable IN (0,1)),
    identity_role         TEXT NOT NULL DEFAULT 'none'
        CHECK (identity_role IN ('none','candidate','key_part')),
    display_order         INTEGER NOT NULL DEFAULT 0 CHECK (display_order >= 0),
    first_seen_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to              TEXT,
    UNIQUE (dataset_definition_id, field_key)
);

CREATE TABLE generic_ingestion (
    generic_ingestion_id  INTEGER PRIMARY KEY,
    dataset_definition_id INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    schema_version_id     INTEGER NOT NULL
        REFERENCES dataset_schema_version(schema_version_id),
    source_snapshot_id    INTEGER NOT NULL
        REFERENCES generic_page_snapshot(page_snapshot_id),
    source_locator        TEXT NOT NULL,
    record_count          INTEGER NOT NULL CHECK (record_count >= 0),
    status                TEXT NOT NULL DEFAULT 'success'
        CHECK (status = 'success'),
    ingested_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (source_snapshot_id, source_locator)
);

CREATE TABLE generic_page_snapshot (
    page_snapshot_id INTEGER PRIMARY KEY,
    source_url       TEXT NOT NULL,
    content_type     TEXT NOT NULL DEFAULT 'text/html'
        CHECK (content_type = 'text/html'),
    html_content     TEXT NOT NULL,
    content_hash     TEXT NOT NULL,
    captured_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
, crawl_run_ref TEXT, html_codec TEXT NOT NULL DEFAULT 'plain', html_dict_id INTEGER REFERENCES snapshot_dictionary(dict_id), run_id INTEGER REFERENCES crawl_run(run_id));

CREATE TABLE generic_record (
    generic_record_id     INTEGER PRIMARY KEY,
    dataset_definition_id INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    record_key            TEXT NOT NULL,
    schema_version_id     INTEGER NOT NULL
        REFERENCES dataset_schema_version(schema_version_id),
    data_json             TEXT NOT NULL
        CHECK (json_valid(data_json) AND json_type(data_json) = 'object'),
    source_snapshot_id    INTEGER NOT NULL
        REFERENCES generic_page_snapshot(page_snapshot_id),
    source_locator        TEXT NOT NULL,
    content_hash          TEXT NOT NULL,
    first_seen_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    status                TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','unavailable','retired')), node_id INTEGER
    GENERATED ALWAYS AS (json_extract(data_json, '$.node_id')) VIRTUAL
    REFERENCES classification_node(node_id), parent_record_key TEXT
    GENERATED ALWAYS AS (json_extract(data_json, '$.parent_record_key')) VIRTUAL,
    UNIQUE (dataset_definition_id, record_key)
);

CREATE TABLE generic_record_revision (
    record_revision_id INTEGER PRIMARY KEY,
    generic_record_id  INTEGER NOT NULL REFERENCES generic_record(generic_record_id),
    schema_version_id  INTEGER NOT NULL
        REFERENCES dataset_schema_version(schema_version_id),
    source_snapshot_id INTEGER NOT NULL
        REFERENCES generic_page_snapshot(page_snapshot_id),
    data_json          TEXT NOT NULL
        CHECK (json_valid(data_json) AND json_type(data_json) = 'object'),
    content_hash       TEXT NOT NULL,
    observed_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (generic_record_id, source_snapshot_id, content_hash)
);

CREATE TABLE "identity_alias" (
    identity_alias_id INTEGER PRIMARY KEY,
    source_product_id INTEGER NOT NULL REFERENCES source_product(source_product_id),
    alias_type        TEXT NOT NULL
        CHECK (alias_type IN ('external_product_id','external_sku','product_link')),
    alias_value       TEXT NOT NULL,
    first_seen_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    retired_at        TEXT     -- when this value stopped being the current one
);

CREATE TABLE job_log_entry (
    job_log_id INTEGER PRIMARY KEY,
    job_id     INTEGER NOT NULL REFERENCES crawl_job(job_id),
    logged_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    level      TEXT NOT NULL DEFAULT 'info'
        CHECK (level IN ('debug','info','warning','error')),
    source_key TEXT,
    message    TEXT NOT NULL
);

CREATE TABLE material (
    material_id              INTEGER PRIMARY KEY,
    material_name_ar         TEXT,
    material_name         TEXT,
    brand_id                 INTEGER REFERENCES brand(brand_id),
    manufacturer_part_number TEXT,
    gtin                     TEXT,           -- barcode/EAN when known (masdaronline delivers real ones)
    material_type            TEXT NOT NULL DEFAULT 'raw_material'
        CHECK (material_type IN ('raw_material','product','accessory','service','commodity')),
    status                   TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','discontinued','needs_review')),
    created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE material_attribute_value (
    material_attribute_value_id INTEGER PRIMARY KEY,
    material_id         INTEGER NOT NULL REFERENCES material(material_id),
    attribute_id        INTEGER NOT NULL REFERENCES attribute_definition(attribute_id),
    raw_value           TEXT,
    numeric_value       REAL,
    normalized_unit_id  INTEGER REFERENCES selling_unit(selling_unit_id),
    source_snapshot_id  INTEGER REFERENCES raw_snapshot(snapshot_id),
    valid_from          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to            TEXT
);

CREATE TABLE material_classification (
    material_classification_id INTEGER PRIMARY KEY,
    material_id INTEGER NOT NULL REFERENCES material(material_id),
    node_id     INTEGER NOT NULL REFERENCES classification_node(node_id),
    is_primary  INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0,1)),
    confidence  REAL NOT NULL DEFAULT 1.0,
    assigned_by TEXT NOT NULL DEFAULT 'manual' CHECK (assigned_by IN ('manual','auto')),
    valid_from  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to    TEXT
);

CREATE TABLE material_variant (
    variant_id       INTEGER PRIMARY KEY,
    material_id      INTEGER NOT NULL REFERENCES material(material_id),
    variant_code     TEXT,
    variant_label     TEXT,
    selling_unit_id  INTEGER REFERENCES selling_unit(selling_unit_id),
    pack_quantity    REAL,
    spec_fingerprint TEXT,
    status           TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','discontinued')),
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE offer_state (
    offer_id            INTEGER PRIMARY KEY REFERENCES source_offer(offer_id),
    price     REAL,
    currency            TEXT,
    availability        TEXT NOT NULL DEFAULT 'unknown',
    stock_quantity      REAL,
    price_hash          TEXT,
    price_fields        TEXT,
    -- Advanced by every successful refresh that saw this offer, whether or
    -- not the price moved. A failed or partial run must NOT advance it.
    last_confirmed_at   TEXT,
    last_seen_at        TEXT,
    first_seen_at       TEXT,
    updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE price_observation (
    price_observation_id INTEGER PRIMARY KEY,
    offer_id             INTEGER NOT NULL REFERENCES source_offer(offer_id),
    observed_at          TEXT NOT NULL,      -- UTC ISO8601: when the price was read
    business_date        TEXT NOT NULL,      -- 'YYYY-MM-DD' working day
    price_before        REAL,
    price_sale           REAL,
    price      REAL NOT NULL,
    currency             TEXT NOT NULL,
    tax_included         INTEGER NOT NULL CHECK (tax_included IN (0,1)),
    availability         TEXT NOT NULL DEFAULT 'unknown'
        CHECK (availability IN ('in_stock','out_of_stock','unknown')),
    stock_quantity       REAL,
    run_id               INTEGER NOT NULL REFERENCES crawl_run(run_id),
    snapshot_id          INTEGER REFERENCES raw_snapshot(snapshot_id),
    record_hash          TEXT NOT NULL       -- hash of price+state; the change/dedupe key
, price_hash TEXT, price_fields TEXT, provenance TEXT NOT NULL DEFAULT 'observed'
    CHECK (provenance IN ('observed','reported')), official_source_name TEXT NOT NULL DEFAULT '', official_source_link  TEXT NOT NULL DEFAULT '', price_trade REAL);

CREATE TABLE "price_period" (
    price_period_id    INTEGER PRIMARY KEY,
    offer_id           INTEGER NOT NULL REFERENCES source_offer(offer_id),
    price_hash         TEXT NOT NULL,
    -- The fields the hash covered. Two periods whose field sets differ are not
    -- comparable, and the boundary between them is the source publishing more
    -- (or less) rather than a price moving.
    price_fields       TEXT NOT NULL DEFAULT '',
    price    REAL,
    price_before      REAL,
    price_sale         REAL,
    currency           TEXT,
    tax_included       INTEGER,
    first_detected_at  TEXT NOT NULL,
    last_confirmed_at  TEXT NOT NULL,
    closed_at          TEXT,
    -- Why this period began: the first price ever seen, a real price change, a
    -- return after an absence, the source changing which fields it publishes,
    -- the source switching the CURRENCY it publishes in, or US changing what a
    -- key MEANS (PRICE_KEY_VERSION) — the last of which is not an event at the
    -- source at all.
    opened_because     TEXT NOT NULL DEFAULT 'price_change'
        CHECK (opened_because IN ('first_seen','price_change','returned',
                                  'fields_changed','currency_change',
                                  'key_version_changed'))
);

CREATE TABLE raw_snapshot (
    snapshot_id  INTEGER PRIMARY KEY,
    run_id       INTEGER NOT NULL REFERENCES crawl_run(run_id),
    source_url   TEXT NOT NULL,
    captured_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    content_type TEXT,
    content_hash TEXT NOT NULL,              -- F4 short-circuit + dedupe key
    storage_path TEXT,                       -- gzipped file on disk (A8)
    http_status  INTEGER
);

CREATE TABLE relationship_field_pair (
    relationship_field_pair_id INTEGER PRIMARY KEY,
    dataset_relationship_id    INTEGER NOT NULL
        REFERENCES dataset_relationship(dataset_relationship_id),
    parent_field_id             INTEGER NOT NULL REFERENCES field_definition(field_definition_id),
    child_field_id              INTEGER NOT NULL REFERENCES field_definition(field_definition_id),
    pair_order                  INTEGER NOT NULL DEFAULT 0 CHECK (pair_order >= 0),
    UNIQUE (dataset_relationship_id, parent_field_id, child_field_id),
    UNIQUE (dataset_relationship_id, pair_order)
);

CREATE TABLE retention_pin (
    retention_pin_id INTEGER PRIMARY KEY,
    offer_id         INTEGER NOT NULL REFERENCES source_offer(offer_id),
    business_date    TEXT NOT NULL,
    record_hash      TEXT NOT NULL,
    note             TEXT NOT NULL DEFAULT '',
    pinned_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (offer_id, business_date, record_hash)
);

CREATE TABLE retention_policy (
    retention_policy_id INTEGER PRIMARY KEY,
    source_key          TEXT NOT NULL UNIQUE,
    detail_days         INTEGER NOT NULL CHECK (detail_days >= 7),
    older_than_action   TEXT NOT NULL CHECK (older_than_action IN (
                            'keep_all',        -- carry every row forward (a no-op)
                            'daily_summary',   -- one row per offer per day
                            'weekly_summary',  -- one row per offer per ISO week
                            'archive_only')),  -- carry nothing but the protected set
    excluded            INTEGER NOT NULL DEFAULT 0 CHECK (excluded IN (0,1)),
    updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE retention_run (
    retention_run_id    INTEGER PRIMARY KEY,
    mode                TEXT NOT NULL CHECK (mode IN ('preview','compact','prune')),
    finished_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    status              TEXT NOT NULL CHECK (status IN ('succeeded','failed','aborted')),
    observations_before INTEGER NOT NULL DEFAULT 0,
    observations_after  INTEGER NOT NULL DEFAULT 0,
    protected_count     INTEGER NOT NULL DEFAULT 0,
    bytes_before        INTEGER NOT NULL DEFAULT 0,
    bytes_after         INTEGER NOT NULL DEFAULT 0,
    sealed_path         TEXT NOT NULL DEFAULT '',
    detail              TEXT NOT NULL DEFAULT ''
);

CREATE TABLE saved_view (
    saved_view_id INTEGER PRIMARY KEY,
    source_key    TEXT NOT NULL,
    view_name     TEXT NOT NULL,
    config_json   TEXT NOT NULL,             -- {columns:[...], sort:..., filters:{...}}
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE "schedule" (
    schedule_id       INTEGER PRIMARY KEY,
    source_key        TEXT NOT NULL UNIQUE,
    frequency         TEXT NOT NULL DEFAULT 'manual'
        CHECK (frequency IN ('manual','daily','weekly')),
    run_at            TEXT NOT NULL DEFAULT '09:00',
    timezone          TEXT NOT NULL DEFAULT 'UTC',
    weekday           INTEGER,
    run_mode          TEXT NOT NULL DEFAULT 'update'
        CHECK (run_mode IN ('initial_crawl','update','full_rebuild',
                            'history_backfill')),
    missed_run_policy TEXT NOT NULL DEFAULT 'run_when_available'
        CHECK (missed_run_policy IN ('run_when_available','skip')),
    overlap_policy    TEXT NOT NULL DEFAULT 'queue'
        CHECK (overlap_policy IN ('queue','skip')),
    enabled           INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
    last_run_at       TEXT,
    next_run_at       TEXT,
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE schema_version_field (
    schema_version_id   INTEGER NOT NULL
        REFERENCES dataset_schema_version(schema_version_id),
    field_definition_id INTEGER NOT NULL
        REFERENCES field_definition(field_definition_id),
    field_order         INTEGER NOT NULL CHECK (field_order >= 0),
    PRIMARY KEY (schema_version_id, field_definition_id),
    UNIQUE (schema_version_id, field_order)
);

CREATE TABLE scrapex_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE selling_unit (
    selling_unit_id INTEGER PRIMARY KEY,
    unit_code       TEXT NOT NULL UNIQUE,   -- 'piece' | 'm' | 'm2' | 'pack' | 'liter' | 'kg' | 'sheet' ...
    name_ar         TEXT,
    name         TEXT
);

CREATE TABLE source_attribute_promotion (
    source_key      TEXT NOT NULL,
    attribute_code  TEXT NOT NULL,
    promoted_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    PRIMARY KEY (source_key, attribute_code)
);

CREATE TABLE source_offer (
    offer_id          INTEGER PRIMARY KEY,
    source_variant_id INTEGER NOT NULL REFERENCES source_variant(source_variant_id),
    branch_id         TEXT,                  -- site branch/store code when present
    country_code_alpha2            TEXT NOT NULL DEFAULT '*',
    customer_segment  TEXT NOT NULL DEFAULT 'retail'
        CHECK (customer_segment IN ('retail','wholesale','contractor','business')),
    selling_unit_id   INTEGER REFERENCES selling_unit(selling_unit_id),
    basis_quantity    REAL NOT NULL DEFAULT 1,   -- price is per how many units
    minimum_quantity  REAL,
    currency          TEXT NOT NULL,
    tax_included      INTEGER NOT NULL CHECK (tax_included IN (0,1))
, quantity_increment REAL, quantity_is_decimal INTEGER NOT NULL DEFAULT 0
    CHECK (quantity_is_decimal IN (0,1)), weight REAL, weight_unit TEXT, selling_unit_raw TEXT, selling_unit_raw_lang TEXT, content_quantity REAL, content_unit_id INTEGER REFERENCES selling_unit(selling_unit_id), unit_basis_provenance TEXT, unit_basis_witness TEXT, status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'superseded')));

CREATE TABLE source_product (
    source_product_id   INTEGER PRIMARY KEY,
    source_id           INTEGER NOT NULL REFERENCES source_site(source_id),
    external_product_id TEXT NOT NULL,       -- the site's own id ('4672', UUID, slug)
    external_sku        TEXT,
    product_name_ar         TEXT,                -- the product's original name at the source
    product_link         TEXT,
    has_variants        INTEGER NOT NULL DEFAULT 0 CHECK (has_variants IN (0,1)),
    raw_specs_json      TEXT,
    curation     TEXT NOT NULL DEFAULT 'inventoried'
        CHECK (curation IN ('inventoried','selected','ignored')),
    first_seen_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    status              TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','vanished','discontinued')), category_path_ar TEXT NOT NULL DEFAULT '', category_external_id TEXT NOT NULL DEFAULT '', product_name TEXT NOT NULL DEFAULT '', product_name_lang TEXT NOT NULL DEFAULT '', category_path TEXT NOT NULL DEFAULT '', parent_sku TEXT NOT NULL DEFAULT '', brand TEXT, brand_ar TEXT, display_method TEXT NOT NULL DEFAULT '',
    UNIQUE (source_id, external_product_id)  -- the owner's mandated constraint
);

CREATE TABLE source_product_attribute (
    source_product_attribute_id INTEGER PRIMARY KEY,
    source_product_id INTEGER NOT NULL
        REFERENCES source_product(source_product_id),
    attribute_code   TEXT NOT NULL,             -- stable key: pa_color, category
    attribute_label  TEXT NOT NULL DEFAULT '',  -- as printed; renames are cosmetic
    raw_value        TEXT NOT NULL,             -- as printed: "100 meters"
    numeric_value    TEXT NOT NULL DEFAULT '',  -- "100" when measurable
    unit_raw         TEXT NOT NULL DEFAULT '',  -- the unit AS WRITTEN
    value_url        TEXT NOT NULL DEFAULT '',
    attribute_group  TEXT NOT NULL DEFAULT '',  -- Attributes | Classification | ...
    lang             TEXT NOT NULL DEFAULT '',
    first_seen_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')), is_site_filter INTEGER NOT NULL DEFAULT 0,

    UNIQUE (source_product_id, attribute_code, raw_value)
);

CREATE TABLE source_product_match (
    source_product_match_id INTEGER PRIMARY KEY,
    source_product_id INTEGER NOT NULL REFERENCES source_product(source_product_id),
    material_id       INTEGER NOT NULL REFERENCES material(material_id),
    confidence        REAL NOT NULL DEFAULT 0,
    match_method      TEXT NOT NULL DEFAULT 'manual',   -- 'gtin' | 'fingerprint' | 'name_fuzzy' | 'brand_category' | 'manual'
    evidence_json     TEXT,
    review_status     TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending','approved','ignored')),
    valid_from        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to          TEXT
);

CREATE TABLE source_variant (
    source_variant_id   INTEGER PRIMARY KEY,
    source_product_id   INTEGER NOT NULL REFERENCES source_product(source_product_id),
    external_variant_id TEXT,                -- '4670' when the platform provides one
    external_sku        TEXT,
    option_fingerprint  TEXT,                -- 'thickness_mm=12' — canonical, sorted, lowercase
    variant_ar        TEXT,                -- what the user sees: '12 mm'
    variant_axes_ar    TEXT,
    first_seen_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
, status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'superseded')), variant TEXT NOT NULL DEFAULT '', variant_axes TEXT NOT NULL DEFAULT '', variant_url TEXT NOT NULL DEFAULT '');

CREATE TABLE source_variant_match (
    source_variant_match_id INTEGER PRIMARY KEY,
    source_variant_id INTEGER NOT NULL REFERENCES source_variant(source_variant_id),
    variant_id        INTEGER NOT NULL REFERENCES material_variant(variant_id),
    confidence        REAL NOT NULL DEFAULT 0,
    match_method      TEXT NOT NULL DEFAULT 'manual',
    evidence_json     TEXT,
    review_status     TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending','approved','ignored')),
    valid_from        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to          TEXT
);

CREATE TABLE tax_rule (
    tax_rule_id     INTEGER PRIMARY KEY,
    source_key      TEXT NOT NULL,
    -- '*' is the source-wide rule; an ISO country code overrides it. GPP needs
    -- both: one general statement for the site, and per-country rules when the
    -- owner supplies evidence for a country that matters to them.
    region          TEXT NOT NULL DEFAULT '*',
    tax_mode        TEXT NOT NULL CHECK (tax_mode IN ('incl','excl','unknown')),
    tax_rate_pct        REAL CHECK (tax_rate_pct IS NULL OR (tax_rate_pct >= 0 AND tax_rate_pct <= 100)),
    tax_evidence        TEXT NOT NULL CHECK (tax_evidence IN ('stated','general','unknown')),
    tax_statement_text  TEXT,
    tax_statement   TEXT,
    tax_statement_lang  TEXT,
    verified_at     TEXT,
    valid_from      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d','now')),
    valid_to        TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')), material_key TEXT NOT NULL DEFAULT '*',

    -- A rate without a source is exactly the assertion this table exists to
    -- prevent. 'stated' must carry both the clause and where to read it.
    CHECK (tax_evidence <> 'stated' OR (tax_rate_pct IS NOT NULL AND tax_statement IS NOT NULL)),
    -- A general statement still has to be readable somewhere.
    CHECK (tax_evidence <> 'general' OR tax_statement IS NOT NULL)
);

CREATE TABLE variant_attribute_value (
    variant_attribute_value_id INTEGER PRIMARY KEY,
    variant_id          INTEGER NOT NULL REFERENCES material_variant(variant_id),
    attribute_id        INTEGER NOT NULL REFERENCES attribute_definition(attribute_id),
    raw_value           TEXT,                -- '3660 مم' exactly as captured
    numeric_value       REAL,                -- 3.66
    normalized_unit_id  INTEGER REFERENCES selling_unit(selling_unit_id),
    source_snapshot_id  INTEGER REFERENCES raw_snapshot(snapshot_id),
    valid_from          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to            TEXT                 -- NULL = current (retirement, never deletion)
);

CREATE TABLE dataset_sighting (
    dataset_sighting_id INTEGER PRIMARY KEY,
    -- The dataset this id belongs to, by KEY rather than by
    -- dataset_definition_id: a sighting can precede the dataset being
    -- defined, which is exactly the case on a first crawl of a new site.
    dataset_key   TEXT NOT NULL,
    -- The site's own identifier, as text. muqawil publishes two id
    -- series in one space — short (881, 5210) and long (20008518) — so a
    -- numeric column would be a claim about a shape the site has not
    -- promised.
    external_id   TEXT NOT NULL,
    first_seen_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    -- How many times any pass has shown it to us. See the header: this
    -- is the capture-recapture sample, not bookkeeping.
    seen_count    INTEGER NOT NULL DEFAULT 1,
    -- The run that saw it FIRST. Nullable for the same reason above.
    first_run_ref TEXT, last_absent_at TEXT, last_absent_run_ref TEXT,
    UNIQUE(dataset_key, external_id)
);

CREATE TABLE snapshot_dictionary (
    dict_id    INTEGER PRIMARY KEY,
    -- What this dictionary is FOR: host plus page kind, e.g.
    -- `muqawil.org/listing`. Per kind and not per host, because the study
    -- measured 187× on listings and 46× on profiles with a same-kind
    -- dictionary; one dictionary for both would be worse than either.
    label      TEXT NOT NULL UNIQUE,
    -- One real page, exactly as it arrived. A raw dictionary rather than a
    -- trained one: trained dictionaries were measured too and reached
    -- 19.7× against the raw page's 187×.
    body       BLOB NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE generic_record_field_change (
    field_change_id     INTEGER PRIMARY KEY,
    generic_record_id   INTEGER NOT NULL
        REFERENCES generic_record(generic_record_id),
    field_definition_id INTEGER NOT NULL
        REFERENCES field_definition(field_definition_id),
    -- NULL means the field did not exist on the row before this change,
    -- which is what a schema moving to v2 looks like from a row's side.
    -- Distinguished from an empty string on purpose: "" is a value the
    -- site published, NULL is the absence of the field itself.
    value_before        TEXT,
    value_after         TEXT,
    source_snapshot_id  INTEGER NOT NULL
        REFERENCES generic_page_snapshot(page_snapshot_id),
    observed_at         TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    -- The same idempotency the revision has: re-running an extraction over
    -- stored pages must not write the same change twice. Per DEC-10 a
    -- corrected parser re-run is expected to be cheap and repeatable.
    UNIQUE (generic_record_id, field_definition_id, source_snapshot_id)
);

CREATE TABLE fetch_validator (
    url            TEXT PRIMARY KEY,
    etag           TEXT,
    last_modified  TEXT,
    seen_at        TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    -- A row that carries neither validator cannot answer the question it
    -- exists for. Refused rather than stored, so "has a validator" and
    -- "has a row" are the same question.
    CHECK (etag IS NOT NULL OR last_modified IS NOT NULL)
);

CREATE TABLE generic_record_node (
    generic_record_id  INTEGER NOT NULL
        REFERENCES generic_record(generic_record_id) ON DELETE CASCADE,
    node_id            INTEGER NOT NULL
        REFERENCES classification_node(node_id),

    -- `R-41`: the DECLARED name of the group this membership belongs to, from
    -- `MULTI_VALUED_GROUPS`. Never the table's position and never its heading —
    -- the detector returns `Table 1`…`Table 5`, three of the five tables share
    -- one heading, and two share a column signature while both being empty.
    group_key          TEXT NOT NULL,

    -- ENFORCED, NOT REMEMBERED. This is F's one real advantage carried across:
    -- every membership names the stored page it was read from, so "why does this
    -- contractor hold this node" is answerable from the warehouse and not from a
    -- log. NOT NULL is the whole point of the column.
    source_snapshot_id INTEGER NOT NULL
        REFERENCES generic_page_snapshot(page_snapshot_id),

    first_seen_at      TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at       TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),

    -- HOW MANY TIMES THIS MEMBERSHIP HAS BEEN READ, and it exists because the
    -- timestamps cannot answer "was this new" — both come from
    -- `strftime(...,'now')` at SECOND resolution, so a first write and its
    -- confirmation in the same second produce `first_seen_at = last_seen_at` and
    -- the caller cannot tell them apart. Measured: a second identical pass over
    -- one profile reported all 25 memberships as new.
    --
    -- `dataset_sighting` already carries a `seen_count` for the same reason, so
    -- this is the schema's existing answer rather than a new idea. The upsert
    -- increments it and returns it, so `= 1` means "written just now" with no
    -- extra read and no dependence on a clock.
    seen_count         INTEGER NOT NULL DEFAULT 1 CHECK (seen_count >= 1), attribute_label TEXT, attribute_value TEXT, attribute_value_ar TEXT,

    -- IDEMPOTENT BY CONSTRUCTION, which is `R-38`'s fourth reason for choosing
    -- D. Shape F would have written these through `approve_candidate` — the
    -- function whose idempotency key `R-40` had to repair. Here a re-parse that
    -- finds the same membership hits this key and updates `last_seen_at`; it
    -- cannot write a duplicate, and no later fix is needed to make that true.
    PRIMARY KEY (generic_record_id, node_id, group_key)
) WITHOUT ROWID;

CREATE TABLE organization_entity (
    organization_id TEXT PRIMARY KEY,
    created_at      TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at      TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
, canonical_organization_id TEXT
    REFERENCES organization_entity(organization_id));

CREATE TABLE organization_source_record (
    enrichment_definition_id INTEGER NOT NULL
        REFERENCES organization_enrichment_definition(enrichment_definition_id)
        ON DELETE CASCADE,
    generic_record_id         INTEGER NOT NULL
        REFERENCES generic_record(generic_record_id) ON DELETE CASCADE,
    organization_id           TEXT NOT NULL
        REFERENCES organization_entity(organization_id),
    source_external_id        TEXT NOT NULL,
    first_seen_at             TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at              TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    PRIMARY KEY (enrichment_definition_id, generic_record_id),
    UNIQUE (enrichment_definition_id, source_external_id)
);

CREATE TABLE organization_fact (
    organization_fact_id INTEGER PRIMARY KEY,
    organization_id      TEXT NOT NULL
        REFERENCES organization_entity(organization_id),
    field_key             TEXT NOT NULL,
    value_json            TEXT NOT NULL CHECK (json_valid(value_json)),
    value_hash            TEXT NOT NULL,
    provider              TEXT NOT NULL,
    source_url            TEXT,
    confidence            REAL NOT NULL DEFAULT 0.0
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    verification_status   TEXT NOT NULL
        CHECK (verification_status IN (
            'verified', 'probable', 'candidate', 'conflict',
            'manual_review', 'not_found')),
    evidence_json         TEXT NOT NULL DEFAULT '{}'
        CHECK (json_valid(evidence_json)
               AND json_type(evidence_json) = 'object'),
    first_seen_at         TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at          TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to              TEXT
, observation_id INTEGER, entity_match_confidence REAL
    CHECK (entity_match_confidence IS NULL OR
           entity_match_confidence BETWEEN 0.0 AND 1.0), extraction_confidence REAL
    CHECK (extraction_confidence IS NULL OR
           extraction_confidence BETWEEN 0.0 AND 1.0), source_authority REAL
    CHECK (source_authority IS NULL OR source_authority BETWEEN 0.0 AND 1.0), observed_at TEXT);

CREATE TABLE organization_enrichment_job (
    job_id                       INTEGER PRIMARY KEY
        REFERENCES crawl_job(job_id) ON DELETE CASCADE,
    enrichment_definition_id     INTEGER NOT NULL
        REFERENCES organization_enrichment_definition(enrichment_definition_id),
    providers_json               TEXT NOT NULL DEFAULT '[]'
        CHECK (json_valid(providers_json)
               AND json_type(providers_json) = 'array'),
    created_at                   TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
, definition_json TEXT NOT NULL DEFAULT '{}'
        CHECK (json_valid(definition_json) AND json_type(definition_json) = 'object'), provider_versions_json TEXT NOT NULL DEFAULT '{}'
        CHECK (json_valid(provider_versions_json)
               AND json_type(provider_versions_json) = 'object'), estimated_requests INTEGER NOT NULL DEFAULT 0
        CHECK (estimated_requests >= 0));

CREATE TABLE organization_identity_alias (
    identity_alias_id       INTEGER PRIMARY KEY,
    organization_id        TEXT NOT NULL
        REFERENCES organization_entity(organization_id),
    alias_type              TEXT NOT NULL
        CHECK (alias_type IN ('source_external_id','domain','phone','registry_id')),
    normalized_value        TEXT NOT NULL,
    value_hash              TEXT NOT NULL,
    source_provider         TEXT NOT NULL,
    confidence              REAL NOT NULL CHECK (confidence BETWEEN 0.0 AND 1.0),
    review_status           TEXT NOT NULL DEFAULT 'candidate'
        CHECK (review_status IN ('candidate','confirmed','rejected')),
    first_seen_at           TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at            TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (organization_id, alias_type, value_hash, source_provider)
);

CREATE TABLE organization_merge_event (
    organization_merge_id  INTEGER PRIMARY KEY,
    source_organization_id TEXT NOT NULL
        REFERENCES organization_entity(organization_id),
    target_organization_id TEXT NOT NULL
        REFERENCES organization_entity(organization_id),
    reviewer               TEXT NOT NULL DEFAULT 'owner',
    reason                 TEXT NOT NULL,
    merged_at              TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    reversed_at            TEXT,
    reversed_by            TEXT,
    reverse_reason         TEXT,
    CHECK (source_organization_id <> target_organization_id)
);

CREATE TABLE organization_merge_member (
    organization_merge_id  INTEGER NOT NULL
        REFERENCES organization_merge_event(organization_merge_id)
        ON DELETE CASCADE,
    organization_id        TEXT NOT NULL
        REFERENCES organization_entity(organization_id),
    previous_canonical_id  TEXT
        REFERENCES organization_entity(organization_id),
    PRIMARY KEY (organization_merge_id, organization_id)
);

CREATE TABLE organization_enrichment_definition_history (
    definition_history_id     INTEGER PRIMARY KEY,
    enrichment_definition_id  INTEGER NOT NULL
        REFERENCES organization_enrichment_definition(enrichment_definition_id)
        ON DELETE CASCADE,
    configuration_version     INTEGER NOT NULL CHECK (configuration_version >= 1),
    definition_json           TEXT NOT NULL
        CHECK (json_valid(definition_json) AND json_type(definition_json) = 'object'),
    replaced_at               TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (enrichment_definition_id, configuration_version)
);

CREATE TABLE organization_enrichment_run_item (
    job_id                  INTEGER NOT NULL
        REFERENCES organization_enrichment_job(job_id) ON DELETE CASCADE,
    generic_record_id       INTEGER NOT NULL,
    source_snapshot_id      INTEGER NOT NULL,
    source_data_json        TEXT CHECK (
        source_data_json IS NULL OR json_valid(source_data_json)),
    source_content_hash     TEXT NOT NULL,
    detail_data_json        TEXT CHECK (
        detail_data_json IS NULL OR json_valid(detail_data_json)),
    detail_content_hash     TEXT,
    source_url              TEXT NOT NULL DEFAULT '',
    source_external_id      TEXT NOT NULL,
    item_status             TEXT NOT NULL DEFAULT 'pending'
        CHECK (item_status IN ('pending','running','completed','failed')),
    attempts                INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    last_error              TEXT,
    completed_at            TEXT,
    PRIMARY KEY (job_id, generic_record_id),
    UNIQUE (job_id, source_external_id)
);

CREATE TABLE organization_provider_observation (
    observation_id          INTEGER PRIMARY KEY,
    job_id                  INTEGER NOT NULL
        REFERENCES organization_enrichment_job(job_id) ON DELETE CASCADE,
    organization_id         TEXT NOT NULL
        REFERENCES organization_entity(organization_id),
    provider                TEXT NOT NULL,
    provider_version        TEXT NOT NULL,
    input_hash              TEXT NOT NULL,
    observation_status      TEXT NOT NULL
        CHECK (observation_status IN (
            'completed','not_found','cached','skipped','failed','system_error')),
    fields_seen_json        TEXT NOT NULL DEFAULT '[]'
        CHECK (json_valid(fields_seen_json)
               AND json_type(fields_seen_json) = 'array'),
    request_count           INTEGER NOT NULL DEFAULT 0 CHECK (request_count >= 0),
    latency_ms              INTEGER NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
    error                   TEXT,
    observed_at             TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (job_id, organization_id, provider)
);

CREATE TABLE organization_review_decision (
    review_decision_id      INTEGER PRIMARY KEY,
    organization_fact_id   INTEGER NOT NULL
        REFERENCES organization_fact(organization_fact_id),
    action                  TEXT NOT NULL
        CHECK (action IN ('approve','reject','override')),
    override_value_json     TEXT CHECK (
        override_value_json IS NULL OR json_valid(override_value_json)),
    reviewer                TEXT NOT NULL DEFAULT 'owner',
    reason                  TEXT NOT NULL DEFAULT '',
    decided_at              TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE "dataset_schema_version" (
    schema_version_id     INTEGER PRIMARY KEY,
    dataset_definition_id INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    version_number        INTEGER NOT NULL CHECK (version_number >= 1),
    schema_hash           TEXT NOT NULL,
    status                TEXT NOT NULL DEFAULT 'approved'
        CHECK (status IN ('approved','retired')),
    approved_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to              TEXT,
    UNIQUE (dataset_definition_id, version_number)
);

CREATE TABLE "source_site" (
    source_id        INTEGER PRIMARY KEY,
    source_key       TEXT NOT NULL UNIQUE,   -- join key with sources.yaml (the Harvest Manifest)
    -- `DEFAULT ''` IS NEW AND DELIBERATE. The column was `NOT NULL` with no default, so
    -- every INSERT had to name it -- and a registration carries no Arabic name, so what
    -- it named was an empty string or, worse, a copy of the English. `SPARK_ESHOP`
    -- already stores '' here, so the column's own history says empty is how "not known"
    -- is spelled; the default makes that the answer instead of each caller's guess.
    source_name_ar   TEXT NOT NULL DEFAULT '', -- 'المدار', 'السويد', ...
    source_name      TEXT NOT NULL DEFAULT '',
    -- `NOT NULL DEFAULT ''`, AND BOTH HALVES WERE MEASURED. `source_site.base_url` was
    -- nullable and `site_profile.base_url` was not; a merge has to take one, and on his
    -- warehouse **zero rows of either table hold a NULL** -- 0 of 12 and 0 of 2 -- so the
    -- stronger constraint costs nothing. The DEFAULT is the second half: without it every
    -- INSERT has to name the column, and a price source is registered from `sources.yaml`
    -- before anyone has said where it lives. Empty is how this table already spells "not
    -- known" in `source_name` and `source_name_ar`; a third column doing it differently
    -- would be the inconsistency, not the rule.
    base_url         TEXT NOT NULL DEFAULT '',
    platform         TEXT,                   -- 'Magento2' | 'Salla' | 'Zid' | 'Shopify' | ... | 'Unknown'
    currency         TEXT,                   -- 'SAR' | 'EGP' | 'USD'
    timezone         TEXT,                   -- 'Asia/Riyadh'
    default_tax_mode TEXT NOT NULL DEFAULT 'incl' CHECK (default_tax_mode IN ('incl','excl')),
    authority        TEXT NOT NULL DEFAULT 'shop' CHECK (authority IN ('official','aggregator','shop')),
    -- FROM `site_profile`, and `lifecycle` replaces `active` on his ruling.
    lifecycle        TEXT NOT NULL DEFAULT 'draft'
        CHECK (lifecycle IN ('draft','active','paused')),
    price_source_key TEXT,
    crawl_scope      TEXT NOT NULL DEFAULT 'listing_only',
    crawl_slice      TEXT,
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to         TEXT
);

CREATE TABLE "dataset_definition" (
    dataset_definition_id INTEGER PRIMARY KEY,
    source_id             INTEGER NOT NULL REFERENCES source_site(source_id),
    dataset_key           TEXT NOT NULL,
    original_name         TEXT NOT NULL,
    display_name          TEXT,
    dataset_kind          TEXT NOT NULL DEFAULT 'unknown'
        CHECK (dataset_kind IN ('table','list','detail','tree','stream','unknown')),
    discovery_method      TEXT NOT NULL
        CHECK (discovery_method IN (
            'manual','html_table','repeating_dom','json','api','inferred')),
    locator_json          TEXT NOT NULL DEFAULT '{}',
    first_seen_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to              TEXT,
    UNIQUE (source_id, dataset_key)
);

CREATE TABLE "dataset_relationship" (
    dataset_relationship_id INTEGER PRIMARY KEY,
    source_id               INTEGER NOT NULL REFERENCES source_site(source_id),
    relationship_key        TEXT NOT NULL,
    parent_dataset_id       INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    child_dataset_id        INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    cardinality             TEXT NOT NULL DEFAULT 'unknown'
        CHECK (cardinality IN (
            'one_to_one','one_to_many','many_to_one','many_to_many','unknown')),
    review_status           TEXT NOT NULL DEFAULT 'suggested'
        CHECK (review_status IN ('suggested','confirmed','rejected')),
    confidence              REAL NOT NULL DEFAULT 0.0
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    evidence_json           TEXT NOT NULL DEFAULT '{}',
    created_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to                TEXT,
    CHECK (parent_dataset_id <> child_dataset_id),
    UNIQUE (source_id, relationship_key)
);

CREATE TABLE "classification_scheme" (
    scheme_id      INTEGER PRIMARY KEY,
    scheme_name_ar TEXT NOT NULL UNIQUE,
    scheme_name    TEXT,
    scheme_type    TEXT NOT NULL CHECK (scheme_type IN ('source','internal','standard')),
    source_id      INTEGER REFERENCES source_site(source_id)  -- set when scheme_type='source'
);

CREATE TABLE "organization_enrichment_definition" (
    enrichment_definition_id INTEGER PRIMARY KEY,
    source_id                 INTEGER NOT NULL
        REFERENCES source_site(source_id),
    source_dataset_id         INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    detail_dataset_id         INTEGER
        REFERENCES dataset_definition(dataset_definition_id),
    output_dataset_id         INTEGER NOT NULL UNIQUE
        REFERENCES dataset_definition(dataset_definition_id),
    entity_key_field          TEXT NOT NULL,
    detail_key_field          TEXT,
    field_mapping_json        TEXT NOT NULL DEFAULT '{}'
        CHECK (json_valid(field_mapping_json)
               AND json_type(field_mapping_json) = 'object'),
    providers_json            TEXT NOT NULL DEFAULT '[]'
        CHECK (json_valid(providers_json)
               AND json_type(providers_json) = 'array'),
    status                    TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'paused', 'retired')),
    created_at                TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at                TEXT NOT NULL
        DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_run_at               TEXT,
    configuration_version     INTEGER NOT NULL DEFAULT 1
        CHECK (configuration_version >= 1),
    UNIQUE (source_dataset_id)
);

CREATE TABLE "crawl_job" (
    job_id             INTEGER PRIMARY KEY,
    job_ref            TEXT NOT NULL UNIQUE,
    run_mode           TEXT NOT NULL
        CHECK (run_mode IN ('initial_crawl','update','full_rebuild',
                            'history_backfill')),
    status             TEXT NOT NULL DEFAULT 'queued' CHECK (status IN (
                           'scheduled','queued','preparing','running','pausing','paused',
                           'resuming','cancelling','cancelled','completed',
                           'completed_with_errors',
                           'partially_completed','failed','requires_review')),
    control            TEXT NOT NULL DEFAULT 'none'
        CHECK (control IN ('none','pause','resume','cancel')),
    source_keys        TEXT NOT NULL,
    current_source_key TEXT,
    stage              TEXT,
    progress_done      INTEGER NOT NULL DEFAULT 0,
    progress_total     INTEGER NOT NULL DEFAULT 0,
    counters_json      TEXT,
    checkpoint_json    TEXT,
    created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    started_at         TEXT,
    finished_at        TEXT,
    last_heartbeat_at  TEXT,
    retry_count        INTEGER NOT NULL DEFAULT 0,
    output_status      TEXT,
    error_summary      TEXT,
    -- THE ONE CHANGE. `directory_crawl` is `scrapex/directoryjob.py`'s `JOB_KIND`, and
    -- `scrapex.jobs.JOB_KINDS` is derived from `SPECIALISED_RUNNERS` so the Python side
    -- cannot list a kind this constraint refuses without a test saying so.
    job_kind           TEXT NOT NULL DEFAULT 'crawl'
        CHECK (job_kind IN ('crawl', 'organization_enrichment', 'directory_crawl'))
);

-- ---- views -------------------------------------------------------------------

CREATE VIEW v_material_price_tracking AS
SELECT
    po.business_date                AS observation_date,
    ss.source_name                  AS source_name,
    ss.source_name_ar               AS source_name_ar,
    m.material_id                   AS material_id,
    COALESCE(m.material_name, m.material_name_ar) AS material_name,
    mv.variant_id                   AS variant_id,
    mv.variant_label                AS variant_label,
    sv.external_sku                 AS external_sku,
    sp.source_product_id            AS source_product_id,
    sv.source_variant_id            AS source_variant_id,
    COALESCE(b.brand_name, sp.brand)    AS brand,
    sp.brand_ar                     AS brand_ar,
    mv.spec_fingerprint             AS specification_summary,
    so.country_code_alpha2          AS country_code_alpha2,
    po.price_before                 AS price_before,
    po.price_sale                   AS price_sale,
    po.price                        AS price,
    po.currency                     AS currency,
    su.unit_code                    AS selling_unit,
    so.basis_quantity               AS basis_quantity,
    po.tax_included                 AS tax_included,
    po.availability                 AS availability,
    po.stock_quantity               AS stock_quantity,
    sp.product_link                 AS product_link,
    po.snapshot_id                  AS snapshot_id
FROM price_observation po
JOIN source_offer so        ON so.offer_id = po.offer_id
JOIN source_variant sv      ON sv.source_variant_id = so.source_variant_id
JOIN source_product sp      ON sp.source_product_id = sv.source_product_id
JOIN source_site ss         ON ss.source_id = sp.source_id
JOIN source_variant_match svm ON svm.source_variant_id = sv.source_variant_id
                             AND svm.review_status = 'approved' AND svm.valid_to IS NULL
JOIN material_variant mv    ON mv.variant_id = svm.variant_id
JOIN material m             ON m.material_id = mv.material_id
LEFT JOIN brand b           ON b.brand_id = m.brand_id
LEFT JOIN selling_unit su   ON su.selling_unit_id = so.selling_unit_id
WHERE po.price_observation_id = COALESCE(
    (SELECT p2.price_observation_id FROM price_observation p2
     WHERE p2.offer_id = po.offer_id AND p2.provenance = 'observed'
     ORDER BY p2.business_date DESC, p2.price_observation_id DESC LIMIT 1),
    po.price_observation_id);

CREATE VIEW v_retention_protected AS
    SELECT po.offer_id, po.business_date, po.record_hash, 'first' AS reason
      FROM price_observation po
      JOIN (SELECT offer_id, MIN(observed_at) AS edge FROM price_observation
             GROUP BY offer_id) e
        ON e.offer_id = po.offer_id AND e.edge = po.observed_at
UNION
    SELECT po.offer_id, po.business_date, po.record_hash, 'latest'
      FROM price_observation po
      JOIN (SELECT offer_id, MAX(observed_at) AS edge FROM price_observation
             GROUP BY offer_id) e
        ON e.offer_id = po.offer_id AND e.edge = po.observed_at
UNION
    SELECT po.offer_id, po.business_date, po.record_hash, 'minimum'
      FROM price_observation po
      JOIN (SELECT offer_id, MIN(price) AS edge FROM price_observation
             WHERE price IS NOT NULL GROUP BY offer_id) e
        ON e.offer_id = po.offer_id AND e.edge = po.price
UNION
    SELECT po.offer_id, po.business_date, po.record_hash, 'maximum'
      FROM price_observation po
      JOIN (SELECT offer_id, MAX(price) AS edge FROM price_observation
             WHERE price IS NOT NULL GROUP BY offer_id) e
        ON e.offer_id = po.offer_id AND e.edge = po.price
UNION
    -- The join is the fix: a pin protects a row only if that row is there.
    SELECT po.offer_id, po.business_date, po.record_hash, 'pinned'
      FROM retention_pin p
      JOIN price_observation po
        ON po.offer_id = p.offer_id
       AND po.business_date = p.business_date
       AND po.record_hash = p.record_hash;

-- ---- indexes -----------------------------------------------------------------

CREATE INDEX ix_absence_period_offer ON absence_period (offer_id, missing_since DESC);

CREATE INDEX ix_change_event_product ON change_event(source_product_id, change_event_id DESC);

CREATE INDEX ix_change_event_run ON change_event(run_id);

CREATE INDEX ix_change_event_time ON change_event(change_event_id DESC);

CREATE INDEX ix_classification_node_parent ON classification_node(parent_node_id);

CREATE INDEX ix_crawl_run_source_time ON crawl_run(source_id, started_at DESC);

CREATE INDEX ix_currency_rate_kind ON currency_rate(currency, source_kind, as_of DESC);

CREATE INDEX ix_currency_rate_latest ON currency_rate(currency, as_of DESC);

CREATE INDEX ix_dataset_field_order ON dataset_field(source_key, display_order);

CREATE INDEX ix_feed_assignment_lookup
    ON feed_assignment(material_id, region) WHERE valid_to IS NULL;

CREATE INDEX ix_field_definition_dataset
    ON field_definition(dataset_definition_id, display_order, field_definition_id);

CREATE INDEX ix_field_definition_paging
    ON field_definition (dataset_definition_id, field_definition_id)
    WHERE valid_to IS NULL;

CREATE INDEX ix_generic_ingestion_dataset
    ON generic_ingestion(dataset_definition_id, generic_ingestion_id);

CREATE INDEX ix_generic_page_snapshot_hash
    ON generic_page_snapshot(content_hash, page_snapshot_id);

CREATE INDEX ix_generic_page_snapshot_page
    ON generic_page_snapshot(page_snapshot_id, captured_at);

CREATE INDEX ix_generic_record_page
    ON generic_record(dataset_definition_id, generic_record_id);

CREATE INDEX ix_generic_record_revision_record
    ON generic_record_revision(generic_record_id, record_revision_id);

CREATE INDEX ix_generic_record_snapshot
    ON generic_record(source_snapshot_id, generic_record_id);

CREATE INDEX ix_identity_alias_value
    ON identity_alias (alias_type, alias_value);

CREATE INDEX ix_job_log_job_time ON job_log_entry(job_id, job_log_id DESC);

CREATE INDEX ix_material_attr_current ON material_attribute_value(material_id, attribute_id) WHERE valid_to IS NULL;

CREATE INDEX ix_material_classification_current
    ON material_classification(material_id) WHERE valid_to IS NULL;

CREATE INDEX ix_material_gtin ON material(gtin) WHERE gtin IS NOT NULL;

CREATE INDEX ix_material_variant_material ON material_variant(material_id);

CREATE INDEX ix_price_obs_offer_pricehash
    ON price_observation (offer_id, observed_at DESC, price_hash);

CREATE INDEX ix_price_obs_offer_time ON price_observation(offer_id, observed_at DESC);

CREATE INDEX ix_price_obs_provenance
    ON price_observation (offer_id, provenance, business_date DESC,
                          price_observation_id DESC);

CREATE INDEX ix_price_period_offer ON price_period (offer_id, first_detected_at DESC);

CREATE INDEX ix_raw_snapshot_hash ON raw_snapshot(content_hash);

CREATE INDEX ix_relationship_field_pair_relationship
    ON relationship_field_pair(dataset_relationship_id, pair_order);

CREATE INDEX ix_retention_pin_offer ON retention_pin (offer_id);

CREATE INDEX ix_schedule_due ON schedule(enabled, next_run_at);

CREATE INDEX ix_schema_version_field_order
    ON schema_version_field(schema_version_id, field_order);

CREATE INDEX ix_source_product_attribute_site_filter
    ON source_product_attribute (source_product_id, is_site_filter);

CREATE INDEX ix_source_product_curation ON source_product(source_id, curation);

CREATE INDEX ix_spa_product ON source_product_attribute(source_product_id);

CREATE INDEX ix_tax_rule_lookup
    ON tax_rule (source_key, region, material_key, valid_from DESC);

CREATE INDEX ix_variant_attr_current ON variant_attribute_value(variant_id, attribute_id) WHERE valid_to IS NULL;

CREATE UNIQUE INDEX ux_absence_period_open ON absence_period (offer_id)
    WHERE returned_at IS NULL;

CREATE UNIQUE INDEX ux_classification_mapping_active
    ON classification_mapping(source_node_id) WHERE valid_to IS NULL AND review_status = 'approved';

CREATE UNIQUE INDEX ux_classification_node_external
    ON classification_node(scheme_id, external_id) WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX ux_dataset_field ON dataset_field(source_key, field_key);

CREATE UNIQUE INDEX ux_feed_assignment_active
    ON feed_assignment(material_id, COALESCE(variant_id,0), region, priority)
    WHERE valid_to IS NULL;

CREATE UNIQUE INDEX ux_identity_alias
    ON identity_alias (source_product_id, alias_type, alias_value);

CREATE UNIQUE INDEX ux_material_variant_fingerprint
    ON material_variant(material_id, spec_fingerprint) WHERE spec_fingerprint IS NOT NULL;

CREATE UNIQUE INDEX ux_price_obs_dedupe ON price_observation(offer_id, business_date, record_hash);

CREATE UNIQUE INDEX ux_price_period_open
    ON price_period (offer_id) WHERE closed_at IS NULL;

CREATE UNIQUE INDEX ux_saved_view_name ON saved_view(source_key, view_name);

CREATE UNIQUE INDEX ux_source_offer_identity
    ON source_offer(source_variant_id, COALESCE(branch_id,''), country_code_alpha2, customer_segment,
                    COALESCE(selling_unit_id,0), basis_quantity);

CREATE UNIQUE INDEX ux_source_product_match_active
    ON source_product_match(source_product_id) WHERE valid_to IS NULL AND review_status = 'approved';

CREATE UNIQUE INDEX ux_source_variant_external
    ON source_variant(source_product_id, external_variant_id)
    WHERE external_variant_id IS NOT NULL;

CREATE UNIQUE INDEX ux_source_variant_fingerprint
    ON source_variant(source_product_id, option_fingerprint)
    WHERE external_variant_id IS NULL AND option_fingerprint IS NOT NULL;

CREATE UNIQUE INDEX ux_source_variant_match_active
    ON source_variant_match(source_variant_id) WHERE valid_to IS NULL AND review_status = 'approved';

CREATE UNIQUE INDEX ux_tax_rule_current
    ON tax_rule (source_key, region, material_key) WHERE valid_to IS NULL;

CREATE INDEX idx_snapshot_run_url
    ON generic_page_snapshot(crawl_run_ref, source_url);

CREATE INDEX idx_sighting_dataset
    ON dataset_sighting(dataset_key, external_id);

CREATE INDEX ix_dataset_sighting_last_seen
    ON dataset_sighting(dataset_key, last_seen_at);

CREATE UNIQUE INDEX ux_classification_node_name
    ON classification_node(scheme_id, ifnull(parent_node_id, 0), node_name_ar);

CREATE INDEX ix_generic_record_node
    ON generic_record(node_id) WHERE node_id IS NOT NULL;

CREATE INDEX ix_generic_record_parent_key
    ON generic_record(parent_record_key) WHERE parent_record_key IS NOT NULL;

CREATE INDEX ix_field_change_record
    ON generic_record_field_change(generic_record_id, observed_at);

CREATE INDEX ix_field_change_field
    ON generic_record_field_change(field_definition_id, observed_at);

CREATE INDEX ix_fetch_validator_seen
    ON fetch_validator(seen_at);

CREATE INDEX ix_record_node_by_node
    ON generic_record_node(node_id, group_key);

CREATE INDEX ix_record_node_by_attribute
    ON generic_record_node(group_key, attribute_value_ar)
    WHERE attribute_value_ar IS NOT NULL;

CREATE INDEX ix_organization_source_record_org
    ON organization_source_record(enrichment_definition_id, organization_id);

CREATE UNIQUE INDEX ux_organization_fact_current
    ON organization_fact(organization_id, field_key, provider)
    WHERE valid_to IS NULL;

CREATE INDEX ix_organization_fact_review
    ON organization_fact(verification_status, organization_id)
    WHERE valid_to IS NULL;

CREATE INDEX ix_organization_entity_canonical
    ON organization_entity(canonical_organization_id);

CREATE INDEX ix_organization_identity_alias_candidates
    ON organization_identity_alias(alias_type, value_hash, review_status);

CREATE INDEX ix_organization_enrichment_run_item_work
    ON organization_enrichment_run_item(job_id, item_status, generic_record_id);

CREATE INDEX ix_organization_provider_observation_fresh
    ON organization_provider_observation(
        organization_id, provider, provider_version, input_hash,
        observation_status, observed_at);

CREATE INDEX ix_organization_review_decision_fact
    ON organization_review_decision(organization_fact_id, review_decision_id DESC);

CREATE INDEX ix_organization_enrichment_job_definition
    ON organization_enrichment_job(enrichment_definition_id, job_id DESC);

CREATE UNIQUE INDEX ux_dataset_schema_version_active
    ON dataset_schema_version(dataset_definition_id)
    WHERE valid_to IS NULL;

CREATE INDEX ix_dataset_definition_site
    ON dataset_definition(source_id, dataset_definition_id, valid_to);

CREATE INDEX ix_dataset_relationship_site
    ON dataset_relationship(source_id, dataset_relationship_id, valid_to);

CREATE INDEX ix_generic_page_snapshot_run ON generic_page_snapshot(run_id);

CREATE INDEX ix_crawl_job_status ON crawl_job(status, created_at DESC);

-- ---- triggers ----------------------------------------------------------------

CREATE TRIGGER trg_generic_ingestion_append_only_delete
BEFORE DELETE ON generic_ingestion
BEGIN
    SELECT RAISE(ABORT, 'generic ingestions are append-only');
END;

CREATE TRIGGER trg_generic_ingestion_append_only_update
BEFORE UPDATE ON generic_ingestion
BEGIN
    SELECT RAISE(ABORT, 'generic ingestions are append-only');
END;

CREATE TRIGGER trg_generic_ingestion_matches_insert
BEFORE INSERT ON generic_ingestion
FOR EACH ROW
WHEN NEW.dataset_definition_id <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'generic ingestion schema must belong to its dataset');
END;

CREATE TRIGGER trg_generic_page_snapshot_immutable_delete
BEFORE DELETE ON generic_page_snapshot
BEGIN
    SELECT RAISE(ABORT, 'saved HTML snapshots are immutable');
END;

CREATE TRIGGER trg_generic_page_snapshot_immutable_update
BEFORE UPDATE ON generic_page_snapshot
BEGIN
    SELECT RAISE(ABORT, 'saved HTML snapshots are immutable');
END;

CREATE TRIGGER trg_generic_record_revision_append_only_delete
BEFORE DELETE ON generic_record_revision
BEGIN
    SELECT RAISE(ABORT, 'generic record revisions are append-only');
END;

CREATE TRIGGER trg_generic_record_revision_append_only_update
BEFORE UPDATE ON generic_record_revision
BEGIN
    SELECT RAISE(ABORT, 'generic record revisions are append-only');
END;

CREATE TRIGGER trg_generic_record_revision_matches_insert
BEFORE INSERT ON generic_record_revision
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1) <>
     (SELECT dataset_definition_id FROM generic_record
      WHERE generic_record_id = NEW.generic_record_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'generic record revision schema must belong to its dataset');
END;

CREATE TRIGGER trg_generic_record_schema_matches_insert
BEFORE INSERT ON generic_record
FOR EACH ROW
WHEN NEW.dataset_definition_id <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'generic record schema must belong to its dataset');
END;

CREATE TRIGGER trg_generic_record_schema_matches_update
BEFORE UPDATE OF dataset_definition_id, schema_version_id ON generic_record
FOR EACH ROW
WHEN NEW.dataset_definition_id <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'generic record schema must belong to its dataset');
END;

CREATE TRIGGER trg_offer_unit_needs_a_witness_insert
BEFORE INSERT ON source_offer
WHEN NEW.selling_unit_id IS NOT NULL
 AND (NEW.unit_basis_provenance IS NULL OR NEW.unit_basis_provenance = ''
   OR NEW.unit_basis_witness IS NULL OR NEW.unit_basis_witness = '')
BEGIN
  SELECT RAISE(ABORT, 'a selling unit must carry its provenance and its witness');
END;

CREATE TRIGGER trg_offer_unit_needs_a_witness_update
BEFORE UPDATE OF selling_unit_id, unit_basis_provenance, unit_basis_witness ON source_offer
WHEN NEW.selling_unit_id IS NOT NULL
 AND (NEW.unit_basis_provenance IS NULL OR NEW.unit_basis_provenance = ''
   OR NEW.unit_basis_witness IS NULL OR NEW.unit_basis_witness = '')
BEGIN
  SELECT RAISE(ABORT, 'a selling unit must carry its provenance and its witness');
END;

CREATE TRIGGER trg_price_obs_no_delete
BEFORE DELETE ON price_observation
BEGIN
    SELECT RAISE(ABORT, 'price_observation is append-only (ENGINEERING.md A7)');
END;

CREATE TRIGGER trg_price_obs_no_update
BEFORE UPDATE ON price_observation
BEGIN
    SELECT RAISE(ABORT, 'price_observation is append-only (ENGINEERING.md A7)');
END;

CREATE TRIGGER trg_relationship_field_pair_matches_insert
BEFORE INSERT ON relationship_field_pair
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.parent_field_id LIMIT 1) <>
     (SELECT parent_dataset_id FROM dataset_relationship
      WHERE dataset_relationship_id = NEW.dataset_relationship_id LIMIT 1)
  OR (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.child_field_id LIMIT 1) <>
     (SELECT child_dataset_id FROM dataset_relationship
      WHERE dataset_relationship_id = NEW.dataset_relationship_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'relationship fields must belong to their mapped datasets');
END;

CREATE TRIGGER trg_relationship_field_pair_matches_update
BEFORE UPDATE OF dataset_relationship_id, parent_field_id, child_field_id
ON relationship_field_pair
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.parent_field_id LIMIT 1) <>
     (SELECT parent_dataset_id FROM dataset_relationship
      WHERE dataset_relationship_id = NEW.dataset_relationship_id LIMIT 1)
  OR (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.child_field_id LIMIT 1) <>
     (SELECT child_dataset_id FROM dataset_relationship
      WHERE dataset_relationship_id = NEW.dataset_relationship_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'relationship fields must belong to their mapped datasets');
END;

CREATE TRIGGER trg_schema_version_field_matches_insert
BEFORE INSERT ON schema_version_field
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.field_definition_id LIMIT 1) <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'schema fields must belong to the schema dataset');
END;

CREATE TRIGGER trg_schema_version_field_matches_update
BEFORE UPDATE OF schema_version_id, field_definition_id ON schema_version_field
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.field_definition_id LIMIT 1) <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'schema fields must belong to the schema dataset');
END;

CREATE TRIGGER trg_snapshot_dictionary_immutable_update
BEFORE UPDATE ON snapshot_dictionary
BEGIN
    SELECT RAISE(ABORT, 'a compression dictionary is immutable: every stored page compressed against it would become unreadable');
END;

CREATE TRIGGER trg_snapshot_dictionary_immutable_delete
BEFORE DELETE ON snapshot_dictionary
BEGIN
    SELECT RAISE(ABORT, 'a compression dictionary cannot be deleted: every stored page compressed against it would become unreadable');
END;

CREATE TRIGGER trg_organization_entity_canonical_cycle_insert
BEFORE INSERT ON organization_entity
FOR EACH ROW
WHEN NEW.canonical_organization_id IS NOT NULL AND (
    NEW.canonical_organization_id = NEW.organization_id OR EXISTS (
        WITH RECURSIVE ancestors(organization_id) AS (
            SELECT NEW.canonical_organization_id
            UNION
            SELECT entity.canonical_organization_id
            FROM organization_entity AS entity
            JOIN ancestors ON entity.organization_id=ancestors.organization_id
            WHERE entity.canonical_organization_id IS NOT NULL
        )
        SELECT 1 FROM ancestors WHERE organization_id=NEW.organization_id
    )
)
BEGIN
    SELECT RAISE(ABORT, 'organization canonical identity cycle');
END;

CREATE TRIGGER trg_organization_entity_canonical_cycle_update
BEFORE UPDATE OF canonical_organization_id ON organization_entity
FOR EACH ROW
WHEN NEW.canonical_organization_id IS NOT NULL AND (
    NEW.canonical_organization_id = NEW.organization_id OR EXISTS (
        WITH RECURSIVE ancestors(organization_id) AS (
            SELECT NEW.canonical_organization_id
            UNION
            SELECT entity.canonical_organization_id
            FROM organization_entity AS entity
            JOIN ancestors ON entity.organization_id=ancestors.organization_id
            WHERE entity.canonical_organization_id IS NOT NULL
        )
        SELECT 1 FROM ancestors WHERE organization_id=NEW.organization_id
    )
)
BEGIN
    SELECT RAISE(ABORT, 'organization canonical identity cycle');
END;

CREATE TRIGGER trg_organization_fact_observation_insert
BEFORE INSERT ON organization_fact
FOR EACH ROW
WHEN NEW.observation_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM organization_provider_observation
                 WHERE observation_id = NEW.observation_id)
BEGIN
    SELECT RAISE(ABORT, 'organization fact references an unknown observation');
END;

CREATE TRIGGER trg_organization_fact_observation_update
BEFORE UPDATE OF observation_id ON organization_fact
FOR EACH ROW
WHEN NEW.observation_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM organization_provider_observation
                 WHERE observation_id = NEW.observation_id)
BEGIN
    SELECT RAISE(ABORT, 'organization fact references an unknown observation');
END;

CREATE TRIGGER trg_organization_observation_delete
BEFORE DELETE ON organization_provider_observation
FOR EACH ROW
BEGIN
    UPDATE organization_fact SET observation_id = NULL
    WHERE observation_id = OLD.observation_id;
END;

CREATE TRIGGER trg_dataset_relationship_same_site_insert
BEFORE INSERT ON dataset_relationship
FOR EACH ROW
WHEN (SELECT source_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.parent_dataset_id LIMIT 1) <> NEW.source_id
  OR (SELECT source_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.child_dataset_id LIMIT 1) <> NEW.source_id
BEGIN
    SELECT RAISE(ABORT, 'relationship datasets must belong to the same source');
END;

CREATE TRIGGER trg_dataset_relationship_same_site_update
BEFORE UPDATE OF source_id, parent_dataset_id, child_dataset_id
ON dataset_relationship
FOR EACH ROW
WHEN (SELECT source_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.parent_dataset_id LIMIT 1) <> NEW.source_id
  OR (SELECT source_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.child_dataset_id LIMIT 1) <> NEW.source_id
BEGIN
    SELECT RAISE(ABORT, 'relationship datasets must belong to the same source');
END;

CREATE TRIGGER trg_enrichment_definition_same_site_insert
BEFORE INSERT ON organization_enrichment_definition
FOR EACH ROW
WHEN (SELECT source_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.source_dataset_id LIMIT 1) <> NEW.source_id
  OR (NEW.detail_dataset_id IS NOT NULL AND
      (SELECT source_id FROM dataset_definition
       WHERE dataset_definition_id = NEW.detail_dataset_id LIMIT 1) <> NEW.source_id)
  OR (SELECT source_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.output_dataset_id LIMIT 1) <> NEW.source_id
BEGIN
    SELECT RAISE(ABORT, 'enrichment datasets must belong to the same source');
END;

CREATE TRIGGER trg_enrichment_definition_same_site_update
BEFORE UPDATE OF source_id, source_dataset_id, detail_dataset_id,
                 output_dataset_id ON organization_enrichment_definition
FOR EACH ROW
WHEN (SELECT source_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.source_dataset_id LIMIT 1) <> NEW.source_id
  OR (NEW.detail_dataset_id IS NOT NULL AND
      (SELECT source_id FROM dataset_definition
       WHERE dataset_definition_id = NEW.detail_dataset_id LIMIT 1) <> NEW.source_id)
  OR (SELECT source_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.output_dataset_id LIMIT 1) <> NEW.source_id
BEGIN
    SELECT RAISE(ABORT, 'enrichment datasets must belong to the same source');
END;

CREATE TRIGGER trg_enrichment_definition_datasets_differ_insert
BEFORE INSERT ON organization_enrichment_definition
FOR EACH ROW
WHEN NEW.source_dataset_id = NEW.output_dataset_id
  OR NEW.detail_dataset_id = NEW.source_dataset_id
  OR NEW.detail_dataset_id = NEW.output_dataset_id
BEGIN
    SELECT RAISE(ABORT, 'the enrichment output must be a new dataset');
END;

CREATE TRIGGER trg_enrichment_definition_datasets_differ_update
BEFORE UPDATE OF source_dataset_id, detail_dataset_id, output_dataset_id
ON organization_enrichment_definition
FOR EACH ROW
WHEN NEW.source_dataset_id = NEW.output_dataset_id
  OR NEW.detail_dataset_id = NEW.source_dataset_id
  OR NEW.detail_dataset_id = NEW.output_dataset_id
BEGIN
    SELECT RAISE(ABORT, 'the enrichment output must be a new dataset');
END;

-- ---- identity and shipped defaults -----------------------------------------

INSERT INTO retention_policy (retention_policy_id, source_key, detail_days, older_than_action, excluded) VALUES
    (1, '*', 3650, 'keep_all', 0);

INSERT INTO scrapex_meta (key, value) VALUES
    ('database_kind', 'engine'),
    ('migration_stream', 'engine');

-- THE VERSION THIS FILE ALREADY IS, not 1. A baseline numbered below a
-- live database's version makes the runner replay this whole schema over
-- it, and there is no IF NOT EXISTS anywhere in here.
PRAGMA user_version = 17;
