-- ScrapeX-Engine, one database, one schema.
--
-- GENERATED by tools/derive_engine_schema.py from the two streams this
-- replaces: the price stream (MarketLens) and the generic stream
-- (General). Do not hand-edit — tests/test_one_schema_carries_both_streams.py
-- re-derives this and fails on any difference.
--
-- 51 tables, 59 indexes, 20 triggers, 2 views.

-- WHAT A FILE IS, before anything reads a table out of it. The
-- application id lives in the SQLite header, so a backup restored into
-- the wrong place is refused rather than half-used. Written from
-- scrapex/database_ids.py, so the two cannot drift apart.
PRAGMA foreign_keys = ON;
PRAGMA application_id = 1398293838;  -- 0x5358454E

-- ---- tables -------------------------------------------------------------

CREATE TABLE absence_period (
    absence_period_id  INTEGER PRIMARY KEY,
    offer_id           INTEGER NOT NULL REFERENCES source_offer(offer_id),
    missing_since      TEXT NOT NULL,
    returned_at        TEXT,
    -- The run that established the absence, so the claim is auditable.
    detected_by_run_id INTEGER REFERENCES crawl_run(run_id)
);

CREATE TABLE attribute_definition (
    attribute_id        INTEGER PRIMARY KEY,
    attribute_code      TEXT NOT NULL UNIQUE,  -- 'length'
    name_ar             TEXT,                  -- 'الطول'
    name             TEXT,
    data_type           TEXT NOT NULL DEFAULT 'text' CHECK (data_type IN ('number','text','bool','date')),
    canonical_unit_id   INTEGER REFERENCES selling_unit(selling_unit_id),
    is_variant_defining INTEGER NOT NULL DEFAULT 0 CHECK (is_variant_defining IN (0,1)),
    is_matching_key     INTEGER NOT NULL DEFAULT 0 CHECK (is_matching_key IN (0,1))
);

CREATE TABLE brand (
    brand_id     INTEGER PRIMARY KEY,
    brand_name   TEXT NOT NULL UNIQUE,
    brand_name_ar TEXT,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE change_event (
    change_event_id   INTEGER PRIMARY KEY,
    source_product_id INTEGER REFERENCES source_product(source_product_id),
    source_variant_id INTEGER REFERENCES source_variant(source_variant_id),
    offer_id          INTEGER REFERENCES source_offer(offer_id),
    field_key         TEXT NOT NULL,        -- 'effective_price' | 'source_name' | 'availability' | ...
    previous_value    TEXT,                 -- NULL for a 'new' event
    new_value         TEXT,
    change_type       TEXT NOT NULL CHECK (change_type IN (
                          'new','field_updated','price_increase','price_decrease',
                          'unavailable','returned','removed')),
    detected_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    run_id            INTEGER REFERENCES crawl_run(run_id),
    job_id            INTEGER REFERENCES crawl_job(job_id)
);

CREATE TABLE classification_mapping (
    classification_mapping_id INTEGER PRIMARY KEY,
    source_node_id INTEGER NOT NULL REFERENCES classification_node(node_id),
    target_node_id INTEGER NOT NULL REFERENCES classification_node(node_id),
    confidence     REAL NOT NULL DEFAULT 1.0,
    mapping_method TEXT NOT NULL DEFAULT 'manual' CHECK (mapping_method IN ('manual','rule','ai')),
    review_status  TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending','approved','ignored')),
    valid_from     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to       TEXT
);

CREATE TABLE classification_node (
    node_id        INTEGER PRIMARY KEY,
    scheme_id      INTEGER NOT NULL REFERENCES classification_scheme(scheme_id),
    parent_node_id INTEGER REFERENCES classification_node(node_id),
    external_id    TEXT,                     -- site category id (madar uid, salla c-id)
    node_code      TEXT,
    node_name_ar      TEXT NOT NULL,
    category_url   TEXT,
    level          INTEGER NOT NULL DEFAULT 1
, node_name TEXT);

CREATE TABLE classification_scheme (
    scheme_id   INTEGER PRIMARY KEY,
    scheme_name_ar TEXT NOT NULL UNIQUE,        -- 'تصنيفات المدار' | 'التصنيف التجاري الداخلي' | 'UNSPSC'
    scheme_type TEXT NOT NULL CHECK (scheme_type IN ('source','internal','standard')),
    source_id   INTEGER REFERENCES source_site(source_id)  -- set when scheme_type='source'
, scheme_name TEXT);

CREATE TABLE "crawl_job" (
    job_id             INTEGER PRIMARY KEY,
    job_ref            TEXT NOT NULL UNIQUE,
    run_mode           TEXT NOT NULL
        CHECK (run_mode IN ('initial_crawl','update','full_rebuild',
                            'history_backfill')),
    status             TEXT NOT NULL DEFAULT 'queued' CHECK (status IN (
                           'scheduled','queued','preparing','running','pausing','paused',
                           'resuming','cancelling','cancelled','completed',
                           'completed_with_errors',
                           'partially_completed','failed','requires_review')),
    control            TEXT NOT NULL DEFAULT 'none'
        CHECK (control IN ('none','pause','resume','cancel')),
    source_keys        TEXT NOT NULL,
    current_source_key TEXT,
    stage              TEXT,
    progress_done      INTEGER NOT NULL DEFAULT 0,
    progress_total     INTEGER NOT NULL DEFAULT 0,
    counters_json      TEXT,
    checkpoint_json    TEXT,
    created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    started_at         TEXT,
    finished_at        TEXT,
    last_heartbeat_at  TEXT,
    retry_count        INTEGER NOT NULL DEFAULT 0,
    output_status      TEXT,
    error_summary      TEXT
);

CREATE TABLE crawl_run (
    run_id              INTEGER PRIMARY KEY,
    source_id           INTEGER NOT NULL REFERENCES source_site(source_id),
    started_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    finished_at         TEXT,
    status              TEXT NOT NULL DEFAULT 'running'
        CHECK (status IN ('running','success','partial','failed')),
    products_discovered INTEGER NOT NULL DEFAULT 0,
    variants_discovered INTEGER NOT NULL DEFAULT 0,
    errors_count        INTEGER NOT NULL DEFAULT 0,
    requests_count      INTEGER NOT NULL DEFAULT 0,    -- F5 politeness accounting
    durations_json      TEXT,                          -- F7 per-phase wall-times
    extractor_version   TEXT
, job_id INTEGER REFERENCES crawl_job(job_id), rows_seen INTEGER NOT NULL DEFAULT 0, warning_count INTEGER NOT NULL DEFAULT 0, first_warning TEXT NOT NULL DEFAULT '');

CREATE TABLE "currency_rate" (
    currency_rate_id INTEGER PRIMARY KEY,
    currency         TEXT NOT NULL,            -- ISO code: EGP, SAR, EUR...
    per_usd          REAL NOT NULL CHECK (per_usd > 0),   -- 1 USD = per_usd currency
    as_of            TEXT NOT NULL,            -- the date the rate speaks for
    source_key       TEXT NOT NULL,            -- who published it
    -- WHAT KIND of publisher that is. 'provider' is a rate service whose
    -- business IS the rate; 'shop' is a storefront we read an implied rate off
    -- its own printed prices. A shop's rate is evidence about that shop, and
    -- must never be mistaken for a market rate.
    source_kind      TEXT NOT NULL CHECK (source_kind IN ('provider', 'shop')),
    recorded_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),

    UNIQUE (currency, as_of, source_key)
);

CREATE TABLE database_migration (
    migration_number INTEGER PRIMARY KEY,
    migration_name   TEXT NOT NULL,
    sha256            TEXT NOT NULL,
    applied_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE dataset_definition (
    dataset_definition_id INTEGER PRIMARY KEY,
    site_profile_id       INTEGER NOT NULL REFERENCES site_profile(site_profile_id),
    dataset_key           TEXT NOT NULL,
    original_name         TEXT NOT NULL,
    display_name          TEXT,
    dataset_kind          TEXT NOT NULL DEFAULT 'unknown'
        CHECK (dataset_kind IN ('table','list','detail','tree','stream','unknown')),
    discovery_method      TEXT NOT NULL
        CHECK (discovery_method IN (
            'manual','html_table','repeating_dom','json','api','inferred')),
    locator_json          TEXT NOT NULL DEFAULT '{}',
    first_seen_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to              TEXT,
    UNIQUE (site_profile_id, dataset_key)
);

CREATE TABLE dataset_field (
    dataset_field_id INTEGER PRIMARY KEY,
    source_key       TEXT NOT NULL,          -- the dataset this column belongs to
    field_key        TEXT NOT NULL,          -- IMMUTABLE identity
    original_name    TEXT NOT NULL,          -- as first discovered; never rewritten
    display_name     TEXT,                   -- NULL = show original_name
    data_type        TEXT NOT NULL DEFAULT 'text'
        CHECK (data_type IN ('text','number','bool','date')),
    is_hidden        INTEGER NOT NULL DEFAULT 0 CHECK (is_hidden IN (0,1)),
    display_order    INTEGER NOT NULL DEFAULT 0,
    first_seen_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
, arranged_at TEXT);

CREATE TABLE dataset_relationship (
    dataset_relationship_id INTEGER PRIMARY KEY,
    site_profile_id         INTEGER NOT NULL REFERENCES site_profile(site_profile_id),
    relationship_key        TEXT NOT NULL,
    parent_dataset_id       INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    child_dataset_id        INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    cardinality             TEXT NOT NULL DEFAULT 'unknown'
        CHECK (cardinality IN (
            'one_to_one','one_to_many','many_to_one','many_to_many','unknown')),
    review_status           TEXT NOT NULL DEFAULT 'suggested'
        CHECK (review_status IN ('suggested','confirmed','rejected')),
    confidence              REAL NOT NULL DEFAULT 0.0
        CHECK (confidence >= 0.0 AND confidence <= 1.0),
    evidence_json           TEXT NOT NULL DEFAULT '{}',
    created_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to                TEXT,
    CHECK (parent_dataset_id <> child_dataset_id),
    UNIQUE (site_profile_id, relationship_key)
);

CREATE TABLE dataset_schema_version (
    schema_version_id     INTEGER PRIMARY KEY,
    dataset_definition_id INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    version_number        INTEGER NOT NULL CHECK (version_number >= 1),
    schema_hash           TEXT NOT NULL,
    status                TEXT NOT NULL DEFAULT 'approved'
        CHECK (status IN ('approved','retired')),
    approved_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to              TEXT,
    UNIQUE (dataset_definition_id, version_number),
    UNIQUE (dataset_definition_id, schema_hash)
);

CREATE TABLE feed_assignment (
    feed_assignment_id INTEGER PRIMARY KEY,
    material_id        INTEGER NOT NULL REFERENCES material(material_id),
    variant_id         INTEGER REFERENCES material_variant(variant_id),  -- NULL = all variants
    region             TEXT NOT NULL DEFAULT '*',
    source_id          INTEGER NOT NULL REFERENCES source_site(source_id),
    priority           INTEGER NOT NULL DEFAULT 1,       -- 1 = designated feeder; 2+ = declared fallbacks
    freshness_days     INTEGER NOT NULL,                 -- max age before this feeder counts stale
    review_status      TEXT NOT NULL DEFAULT 'approved'
        CHECK (review_status IN ('approved','pending','retired')),
    valid_from         TEXT NOT NULL DEFAULT (date('now')),
    valid_to           TEXT,                             -- temporal history; never DELETE
    notes              TEXT
);

CREATE TABLE field_definition (
    field_definition_id   INTEGER PRIMARY KEY,
    dataset_definition_id INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    field_key             TEXT NOT NULL,
    original_name         TEXT NOT NULL,
    display_name          TEXT,
    data_type             TEXT NOT NULL DEFAULT 'unknown'
        CHECK (data_type IN (
            'text','integer','decimal','boolean','date','datetime','url','json','unknown')),
    is_nullable           INTEGER NOT NULL DEFAULT 1 CHECK (is_nullable IN (0,1)),
    identity_role         TEXT NOT NULL DEFAULT 'none'
        CHECK (identity_role IN ('none','candidate','key_part')),
    display_order         INTEGER NOT NULL DEFAULT 0 CHECK (display_order >= 0),
    first_seen_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to              TEXT,
    UNIQUE (dataset_definition_id, field_key)
);

CREATE TABLE generic_ingestion (
    generic_ingestion_id  INTEGER PRIMARY KEY,
    dataset_definition_id INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    schema_version_id     INTEGER NOT NULL
        REFERENCES dataset_schema_version(schema_version_id),
    source_snapshot_id    INTEGER NOT NULL
        REFERENCES generic_page_snapshot(page_snapshot_id),
    source_locator        TEXT NOT NULL,
    record_count          INTEGER NOT NULL CHECK (record_count >= 0),
    status                TEXT NOT NULL DEFAULT 'success'
        CHECK (status = 'success'),
    ingested_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (source_snapshot_id, source_locator)
);

CREATE TABLE generic_page_snapshot (
    page_snapshot_id INTEGER PRIMARY KEY,
    source_url       TEXT NOT NULL,
    content_type     TEXT NOT NULL DEFAULT 'text/html'
        CHECK (content_type = 'text/html'),
    html_content     TEXT NOT NULL,
    content_hash     TEXT NOT NULL,
    captured_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE generic_record (
    generic_record_id     INTEGER PRIMARY KEY,
    dataset_definition_id INTEGER NOT NULL
        REFERENCES dataset_definition(dataset_definition_id),
    record_key            TEXT NOT NULL,
    schema_version_id     INTEGER NOT NULL
        REFERENCES dataset_schema_version(schema_version_id),
    data_json             TEXT NOT NULL
        CHECK (json_valid(data_json) AND json_type(data_json) = 'object'),
    source_snapshot_id    INTEGER NOT NULL
        REFERENCES generic_page_snapshot(page_snapshot_id),
    source_locator        TEXT NOT NULL,
    content_hash          TEXT NOT NULL,
    first_seen_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    status                TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','unavailable','retired')),
    UNIQUE (dataset_definition_id, record_key)
);

CREATE TABLE generic_record_revision (
    record_revision_id INTEGER PRIMARY KEY,
    generic_record_id  INTEGER NOT NULL REFERENCES generic_record(generic_record_id),
    schema_version_id  INTEGER NOT NULL
        REFERENCES dataset_schema_version(schema_version_id),
    source_snapshot_id INTEGER NOT NULL
        REFERENCES generic_page_snapshot(page_snapshot_id),
    data_json          TEXT NOT NULL
        CHECK (json_valid(data_json) AND json_type(data_json) = 'object'),
    content_hash       TEXT NOT NULL,
    observed_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (generic_record_id, source_snapshot_id, content_hash)
);

CREATE TABLE "identity_alias" (
    identity_alias_id INTEGER PRIMARY KEY,
    source_product_id INTEGER NOT NULL REFERENCES source_product(source_product_id),
    alias_type        TEXT NOT NULL
        CHECK (alias_type IN ('external_product_id','external_sku','product_link')),
    alias_value       TEXT NOT NULL,
    first_seen_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    retired_at        TEXT     -- when this value stopped being the current one
);

CREATE TABLE job_log_entry (
    job_log_id INTEGER PRIMARY KEY,
    job_id     INTEGER NOT NULL REFERENCES crawl_job(job_id),
    logged_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    level      TEXT NOT NULL DEFAULT 'info'
        CHECK (level IN ('debug','info','warning','error')),
    source_key TEXT,
    message    TEXT NOT NULL
);

CREATE TABLE material (
    material_id              INTEGER PRIMARY KEY,
    material_name_ar         TEXT,
    material_name         TEXT,
    brand_id                 INTEGER REFERENCES brand(brand_id),
    manufacturer_part_number TEXT,
    gtin                     TEXT,           -- barcode/EAN when known (masdaronline delivers real ones)
    material_type            TEXT NOT NULL DEFAULT 'raw_material'
        CHECK (material_type IN ('raw_material','product','accessory','service','commodity')),
    status                   TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','discontinued','needs_review')),
    created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE material_attribute_value (
    material_attribute_value_id INTEGER PRIMARY KEY,
    material_id         INTEGER NOT NULL REFERENCES material(material_id),
    attribute_id        INTEGER NOT NULL REFERENCES attribute_definition(attribute_id),
    raw_value           TEXT,
    numeric_value       REAL,
    normalized_unit_id  INTEGER REFERENCES selling_unit(selling_unit_id),
    source_snapshot_id  INTEGER REFERENCES raw_snapshot(snapshot_id),
    valid_from          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to            TEXT
);

CREATE TABLE material_classification (
    material_classification_id INTEGER PRIMARY KEY,
    material_id INTEGER NOT NULL REFERENCES material(material_id),
    node_id     INTEGER NOT NULL REFERENCES classification_node(node_id),
    is_primary  INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0,1)),
    confidence  REAL NOT NULL DEFAULT 1.0,
    assigned_by TEXT NOT NULL DEFAULT 'manual' CHECK (assigned_by IN ('manual','auto')),
    valid_from  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to    TEXT
);

CREATE TABLE material_variant (
    variant_id       INTEGER PRIMARY KEY,
    material_id      INTEGER NOT NULL REFERENCES material(material_id),
    variant_code     TEXT,
    variant_label     TEXT,
    selling_unit_id  INTEGER REFERENCES selling_unit(selling_unit_id),
    pack_quantity    REAL,
    spec_fingerprint TEXT,
    status           TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','discontinued')),
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE offer_state (
    offer_id            INTEGER PRIMARY KEY REFERENCES source_offer(offer_id),
    price     REAL,
    currency            TEXT,
    availability        TEXT NOT NULL DEFAULT 'unknown',
    stock_quantity      REAL,
    price_hash          TEXT,
    price_fields        TEXT,
    -- Advanced by every successful refresh that saw this offer, whether or
    -- not the price moved. A failed or partial run must NOT advance it.
    last_confirmed_at   TEXT,
    last_seen_at        TEXT,
    first_seen_at       TEXT,
    updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE price_observation (
    price_observation_id INTEGER PRIMARY KEY,
    offer_id             INTEGER NOT NULL REFERENCES source_offer(offer_id),
    observed_at          TEXT NOT NULL,      -- UTC ISO8601: when the price was read
    business_date        TEXT NOT NULL,      -- 'YYYY-MM-DD' working day
    price_before        REAL,
    price_sale           REAL,
    price      REAL NOT NULL,
    currency             TEXT NOT NULL,
    tax_included         INTEGER NOT NULL CHECK (tax_included IN (0,1)),
    availability         TEXT NOT NULL DEFAULT 'unknown'
        CHECK (availability IN ('in_stock','out_of_stock','unknown')),
    stock_quantity       REAL,
    run_id               INTEGER NOT NULL REFERENCES crawl_run(run_id),
    snapshot_id          INTEGER REFERENCES raw_snapshot(snapshot_id),
    record_hash          TEXT NOT NULL       -- hash of price+state; the change/dedupe key
, price_hash TEXT, price_fields TEXT, provenance TEXT NOT NULL DEFAULT 'observed'
    CHECK (provenance IN ('observed','reported')), official_source_name TEXT NOT NULL DEFAULT '', official_source_link  TEXT NOT NULL DEFAULT '', price_trade REAL);

CREATE TABLE "price_period" (
    price_period_id    INTEGER PRIMARY KEY,
    offer_id           INTEGER NOT NULL REFERENCES source_offer(offer_id),
    price_hash         TEXT NOT NULL,
    -- The fields the hash covered. Two periods whose field sets differ are not
    -- comparable, and the boundary between them is the source publishing more
    -- (or less) rather than a price moving.
    price_fields       TEXT NOT NULL DEFAULT '',
    price    REAL,
    price_before      REAL,
    price_sale         REAL,
    currency           TEXT,
    tax_included       INTEGER,
    first_detected_at  TEXT NOT NULL,
    last_confirmed_at  TEXT NOT NULL,
    closed_at          TEXT,
    -- Why this period began: the first price ever seen, a real price change, a
    -- return after an absence, the source changing which fields it publishes,
    -- the source switching the CURRENCY it publishes in, or US changing what a
    -- key MEANS (PRICE_KEY_VERSION) — the last of which is not an event at the
    -- source at all.
    opened_because     TEXT NOT NULL DEFAULT 'price_change'
        CHECK (opened_because IN ('first_seen','price_change','returned',
                                  'fields_changed','currency_change',
                                  'key_version_changed'))
);

CREATE TABLE raw_snapshot (
    snapshot_id  INTEGER PRIMARY KEY,
    run_id       INTEGER NOT NULL REFERENCES crawl_run(run_id),
    source_url   TEXT NOT NULL,
    captured_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    content_type TEXT,
    content_hash TEXT NOT NULL,              -- F4 short-circuit + dedupe key
    storage_path TEXT,                       -- gzipped file on disk (A8)
    http_status  INTEGER
);

CREATE TABLE relationship_field_pair (
    relationship_field_pair_id INTEGER PRIMARY KEY,
    dataset_relationship_id    INTEGER NOT NULL
        REFERENCES dataset_relationship(dataset_relationship_id),
    parent_field_id             INTEGER NOT NULL REFERENCES field_definition(field_definition_id),
    child_field_id              INTEGER NOT NULL REFERENCES field_definition(field_definition_id),
    pair_order                  INTEGER NOT NULL DEFAULT 0 CHECK (pair_order >= 0),
    UNIQUE (dataset_relationship_id, parent_field_id, child_field_id),
    UNIQUE (dataset_relationship_id, pair_order)
);

CREATE TABLE retention_pin (
    retention_pin_id INTEGER PRIMARY KEY,
    offer_id         INTEGER NOT NULL REFERENCES source_offer(offer_id),
    business_date    TEXT NOT NULL,
    record_hash      TEXT NOT NULL,
    note             TEXT NOT NULL DEFAULT '',
    pinned_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    UNIQUE (offer_id, business_date, record_hash)
);

CREATE TABLE retention_policy (
    retention_policy_id INTEGER PRIMARY KEY,
    source_key          TEXT NOT NULL UNIQUE,
    detail_days         INTEGER NOT NULL CHECK (detail_days >= 7),
    older_than_action   TEXT NOT NULL CHECK (older_than_action IN (
                            'keep_all',        -- carry every row forward (a no-op)
                            'daily_summary',   -- one row per offer per day
                            'weekly_summary',  -- one row per offer per ISO week
                            'archive_only')),  -- carry nothing but the protected set
    excluded            INTEGER NOT NULL DEFAULT 0 CHECK (excluded IN (0,1)),
    updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE retention_run (
    retention_run_id    INTEGER PRIMARY KEY,
    mode                TEXT NOT NULL CHECK (mode IN ('preview','compact','prune')),
    finished_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    status              TEXT NOT NULL CHECK (status IN ('succeeded','failed','aborted')),
    observations_before INTEGER NOT NULL DEFAULT 0,
    observations_after  INTEGER NOT NULL DEFAULT 0,
    protected_count     INTEGER NOT NULL DEFAULT 0,
    bytes_before        INTEGER NOT NULL DEFAULT 0,
    bytes_after         INTEGER NOT NULL DEFAULT 0,
    sealed_path         TEXT NOT NULL DEFAULT '',
    detail              TEXT NOT NULL DEFAULT ''
);

CREATE TABLE saved_view (
    saved_view_id INTEGER PRIMARY KEY,
    source_key    TEXT NOT NULL,
    view_name     TEXT NOT NULL,
    config_json   TEXT NOT NULL,             -- {columns:[...], sort:..., filters:{...}}
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE "schedule" (
    schedule_id       INTEGER PRIMARY KEY,
    source_key        TEXT NOT NULL UNIQUE,
    frequency         TEXT NOT NULL DEFAULT 'manual'
        CHECK (frequency IN ('manual','daily','weekly')),
    run_at            TEXT NOT NULL DEFAULT '09:00',
    timezone          TEXT NOT NULL DEFAULT 'UTC',
    weekday           INTEGER,
    run_mode          TEXT NOT NULL DEFAULT 'update'
        CHECK (run_mode IN ('initial_crawl','update','full_rebuild',
                            'history_backfill')),
    missed_run_policy TEXT NOT NULL DEFAULT 'run_when_available'
        CHECK (missed_run_policy IN ('run_when_available','skip')),
    overlap_policy    TEXT NOT NULL DEFAULT 'queue'
        CHECK (overlap_policy IN ('queue','skip')),
    enabled           INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
    last_run_at       TEXT,
    next_run_at       TEXT,
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE TABLE schema_version_field (
    schema_version_id   INTEGER NOT NULL
        REFERENCES dataset_schema_version(schema_version_id),
    field_definition_id INTEGER NOT NULL
        REFERENCES field_definition(field_definition_id),
    field_order         INTEGER NOT NULL CHECK (field_order >= 0),
    PRIMARY KEY (schema_version_id, field_definition_id),
    UNIQUE (schema_version_id, field_order)
);

CREATE TABLE scrapex_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE selling_unit (
    selling_unit_id INTEGER PRIMARY KEY,
    unit_code       TEXT NOT NULL UNIQUE,   -- 'piece' | 'm' | 'm2' | 'pack' | 'liter' | 'kg' | 'sheet' ...
    name_ar         TEXT,
    name         TEXT
);

CREATE TABLE site_profile (
    site_profile_id      INTEGER PRIMARY KEY,
    site_key             TEXT NOT NULL UNIQUE,
    display_name         TEXT NOT NULL,
    base_url             TEXT NOT NULL,
    marketlens_source_key TEXT,
    lifecycle            TEXT NOT NULL DEFAULT 'draft'
        CHECK (lifecycle IN ('draft','active','paused')),
    created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to             TEXT
);

CREATE TABLE source_attribute_promotion (
    source_key      TEXT NOT NULL,
    attribute_code  TEXT NOT NULL,
    promoted_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    PRIMARY KEY (source_key, attribute_code)
);

CREATE TABLE source_offer (
    offer_id          INTEGER PRIMARY KEY,
    source_variant_id INTEGER NOT NULL REFERENCES source_variant(source_variant_id),
    branch_id         TEXT,                  -- site branch/store code when present
    country_code_alpha2            TEXT NOT NULL DEFAULT '*',
    customer_segment  TEXT NOT NULL DEFAULT 'retail'
        CHECK (customer_segment IN ('retail','wholesale','contractor','business')),
    selling_unit_id   INTEGER REFERENCES selling_unit(selling_unit_id),
    basis_quantity    REAL NOT NULL DEFAULT 1,   -- price is per how many units
    minimum_quantity  REAL,
    currency          TEXT NOT NULL,
    tax_included      INTEGER NOT NULL CHECK (tax_included IN (0,1))
, quantity_increment REAL, quantity_is_decimal INTEGER NOT NULL DEFAULT 0
    CHECK (quantity_is_decimal IN (0,1)), weight REAL, weight_unit TEXT, selling_unit_raw TEXT, selling_unit_raw_lang TEXT, content_quantity REAL, content_unit_id INTEGER REFERENCES selling_unit(selling_unit_id), unit_basis_provenance TEXT, unit_basis_witness TEXT, status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'superseded')));

CREATE TABLE source_product (
    source_product_id   INTEGER PRIMARY KEY,
    source_id           INTEGER NOT NULL REFERENCES source_site(source_id),
    external_product_id TEXT NOT NULL,       -- the site's own id ('4672', UUID, slug)
    external_sku        TEXT,
    product_name_ar         TEXT,                -- the product's original name at the source
    product_link         TEXT,
    has_variants        INTEGER NOT NULL DEFAULT 0 CHECK (has_variants IN (0,1)),
    raw_specs_json      TEXT,
    curation     TEXT NOT NULL DEFAULT 'inventoried'
        CHECK (curation IN ('inventoried','selected','ignored')),
    first_seen_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    status              TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','vanished','discontinued')), category_path_ar TEXT NOT NULL DEFAULT '', category_external_id TEXT NOT NULL DEFAULT '', product_name TEXT NOT NULL DEFAULT '', product_name_lang TEXT NOT NULL DEFAULT '', category_path TEXT NOT NULL DEFAULT '', parent_sku TEXT NOT NULL DEFAULT '', brand TEXT, brand_ar TEXT, display_method TEXT NOT NULL DEFAULT '',
    UNIQUE (source_id, external_product_id)  -- the owner's mandated constraint
);

CREATE TABLE source_product_attribute (
    source_product_attribute_id INTEGER PRIMARY KEY,
    source_product_id INTEGER NOT NULL
        REFERENCES source_product(source_product_id),
    attribute_code   TEXT NOT NULL,             -- stable key: pa_color, category
    attribute_label  TEXT NOT NULL DEFAULT '',  -- as printed; renames are cosmetic
    raw_value        TEXT NOT NULL,             -- as printed: "100 meters"
    numeric_value    TEXT NOT NULL DEFAULT '',  -- "100" when measurable
    unit_raw         TEXT NOT NULL DEFAULT '',  -- the unit AS WRITTEN
    value_url        TEXT NOT NULL DEFAULT '',
    attribute_group  TEXT NOT NULL DEFAULT '',  -- Attributes | Classification | ...
    lang             TEXT NOT NULL DEFAULT '',
    first_seen_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')), is_site_filter INTEGER NOT NULL DEFAULT 0,

    UNIQUE (source_product_id, attribute_code, raw_value)
);

CREATE TABLE source_product_match (
    source_product_match_id INTEGER PRIMARY KEY,
    source_product_id INTEGER NOT NULL REFERENCES source_product(source_product_id),
    material_id       INTEGER NOT NULL REFERENCES material(material_id),
    confidence        REAL NOT NULL DEFAULT 0,
    match_method      TEXT NOT NULL DEFAULT 'manual',   -- 'gtin' | 'fingerprint' | 'name_fuzzy' | 'brand_category' | 'manual'
    evidence_json     TEXT,
    review_status     TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending','approved','ignored')),
    valid_from        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to          TEXT
);

CREATE TABLE source_site (
    source_id        INTEGER PRIMARY KEY,
    source_key       TEXT NOT NULL UNIQUE,   -- join key with sources.yaml (the Harvest Manifest)
    source_name_ar      TEXT NOT NULL,          -- 'المدار', 'السويد', ...
    base_url         TEXT,
    platform         TEXT,                   -- 'Magento2' | 'Salla' | 'Zid' | 'Shopify' | ... | 'Unknown'
    currency         TEXT,                   -- 'SAR' | 'EGP' | 'USD'
    timezone         TEXT,                   -- 'Asia/Riyadh'
    default_tax_mode TEXT NOT NULL DEFAULT 'incl' CHECK (default_tax_mode IN ('incl','excl')),
    authority        TEXT NOT NULL DEFAULT 'shop' CHECK (authority IN ('official','aggregator','shop')),
    active           INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1))
, source_name TEXT NOT NULL DEFAULT '');

CREATE TABLE source_variant (
    source_variant_id   INTEGER PRIMARY KEY,
    source_product_id   INTEGER NOT NULL REFERENCES source_product(source_product_id),
    external_variant_id TEXT,                -- '4670' when the platform provides one
    external_sku        TEXT,
    option_fingerprint  TEXT,                -- 'thickness_mm=12' — canonical, sorted, lowercase
    variant_ar        TEXT,                -- what the user sees: '12 mm'
    variant_axes_ar    TEXT,
    first_seen_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    last_seen_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
, status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'superseded')), variant TEXT NOT NULL DEFAULT '', variant_axes TEXT NOT NULL DEFAULT '', variant_url TEXT NOT NULL DEFAULT '');

CREATE TABLE source_variant_match (
    source_variant_match_id INTEGER PRIMARY KEY,
    source_variant_id INTEGER NOT NULL REFERENCES source_variant(source_variant_id),
    variant_id        INTEGER NOT NULL REFERENCES material_variant(variant_id),
    confidence        REAL NOT NULL DEFAULT 0,
    match_method      TEXT NOT NULL DEFAULT 'manual',
    evidence_json     TEXT,
    review_status     TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending','approved','ignored')),
    valid_from        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to          TEXT
);

CREATE TABLE tax_rule (
    tax_rule_id     INTEGER PRIMARY KEY,
    source_key      TEXT NOT NULL,
    -- '*' is the source-wide rule; an ISO country code overrides it. GPP needs
    -- both: one general statement for the site, and per-country rules when the
    -- owner supplies evidence for a country that matters to them.
    region          TEXT NOT NULL DEFAULT '*',
    tax_mode        TEXT NOT NULL CHECK (tax_mode IN ('incl','excl','unknown')),
    tax_rate_pct        REAL CHECK (tax_rate_pct IS NULL OR (tax_rate_pct >= 0 AND tax_rate_pct <= 100)),
    tax_evidence        TEXT NOT NULL CHECK (tax_evidence IN ('stated','general','unknown')),
    tax_statement_text  TEXT,
    tax_statement   TEXT,
    tax_statement_lang  TEXT,
    verified_at     TEXT,
    valid_from      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d','now')),
    valid_to        TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')), material_key TEXT NOT NULL DEFAULT '*',

    -- A rate without a source is exactly the assertion this table exists to
    -- prevent. 'stated' must carry both the clause and where to read it.
    CHECK (tax_evidence <> 'stated' OR (tax_rate_pct IS NOT NULL AND tax_statement IS NOT NULL)),
    -- A general statement still has to be readable somewhere.
    CHECK (tax_evidence <> 'general' OR tax_statement IS NOT NULL)
);

CREATE TABLE variant_attribute_value (
    variant_attribute_value_id INTEGER PRIMARY KEY,
    variant_id          INTEGER NOT NULL REFERENCES material_variant(variant_id),
    attribute_id        INTEGER NOT NULL REFERENCES attribute_definition(attribute_id),
    raw_value           TEXT,                -- '3660 مم' exactly as captured
    numeric_value       REAL,                -- 3.66
    normalized_unit_id  INTEGER REFERENCES selling_unit(selling_unit_id),
    source_snapshot_id  INTEGER REFERENCES raw_snapshot(snapshot_id),
    valid_from          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    valid_to            TEXT                 -- NULL = current (retirement, never deletion)
);

-- ---- views --------------------------------------------------------------

CREATE VIEW v_material_price_tracking AS
SELECT
    po.business_date                AS observation_date,
    ss.source_name                  AS source_name,
    ss.source_name_ar               AS source_name_ar,
    m.material_id                   AS material_id,
    COALESCE(m.material_name, m.material_name_ar) AS material_name,
    mv.variant_id                   AS variant_id,
    mv.variant_label                AS variant_label,
    sv.external_sku                 AS external_sku,
    sp.source_product_id            AS source_product_id,
    sv.source_variant_id            AS source_variant_id,
    COALESCE(b.brand_name, sp.brand)    AS brand,
    sp.brand_ar                     AS brand_ar,
    mv.spec_fingerprint             AS specification_summary,
    so.country_code_alpha2          AS country_code_alpha2,
    po.price_before                 AS price_before,
    po.price_sale                   AS price_sale,
    po.price                        AS price,
    po.currency                     AS currency,
    su.unit_code                    AS selling_unit,
    so.basis_quantity               AS basis_quantity,
    po.tax_included                 AS tax_included,
    po.availability                 AS availability,
    po.stock_quantity               AS stock_quantity,
    sp.product_link                 AS product_link,
    po.snapshot_id                  AS snapshot_id
FROM price_observation po
JOIN source_offer so        ON so.offer_id = po.offer_id
JOIN source_variant sv      ON sv.source_variant_id = so.source_variant_id
JOIN source_product sp      ON sp.source_product_id = sv.source_product_id
JOIN source_site ss         ON ss.source_id = sp.source_id
JOIN source_variant_match svm ON svm.source_variant_id = sv.source_variant_id
                             AND svm.review_status = 'approved' AND svm.valid_to IS NULL
JOIN material_variant mv    ON mv.variant_id = svm.variant_id
JOIN material m             ON m.material_id = mv.material_id
LEFT JOIN brand b           ON b.brand_id = m.brand_id
LEFT JOIN selling_unit su   ON su.selling_unit_id = so.selling_unit_id
WHERE po.price_observation_id = COALESCE(
    (SELECT p2.price_observation_id FROM price_observation p2
     WHERE p2.offer_id = po.offer_id AND p2.provenance = 'observed'
     ORDER BY p2.business_date DESC, p2.price_observation_id DESC LIMIT 1),
    po.price_observation_id);

CREATE VIEW v_retention_protected AS
    SELECT po.offer_id, po.business_date, po.record_hash, 'first' AS reason
      FROM price_observation po
      JOIN (SELECT offer_id, MIN(observed_at) AS edge FROM price_observation
             GROUP BY offer_id) e
        ON e.offer_id = po.offer_id AND e.edge = po.observed_at
UNION
    SELECT po.offer_id, po.business_date, po.record_hash, 'latest'
      FROM price_observation po
      JOIN (SELECT offer_id, MAX(observed_at) AS edge FROM price_observation
             GROUP BY offer_id) e
        ON e.offer_id = po.offer_id AND e.edge = po.observed_at
UNION
    SELECT po.offer_id, po.business_date, po.record_hash, 'minimum'
      FROM price_observation po
      JOIN (SELECT offer_id, MIN(price) AS edge FROM price_observation
             WHERE price IS NOT NULL GROUP BY offer_id) e
        ON e.offer_id = po.offer_id AND e.edge = po.price
UNION
    SELECT po.offer_id, po.business_date, po.record_hash, 'maximum'
      FROM price_observation po
      JOIN (SELECT offer_id, MAX(price) AS edge FROM price_observation
             WHERE price IS NOT NULL GROUP BY offer_id) e
        ON e.offer_id = po.offer_id AND e.edge = po.price
UNION
    -- The join is the fix: a pin protects a row only if that row is there.
    SELECT po.offer_id, po.business_date, po.record_hash, 'pinned'
      FROM retention_pin p
      JOIN price_observation po
        ON po.offer_id = p.offer_id
       AND po.business_date = p.business_date
       AND po.record_hash = p.record_hash;

-- ---- indexs -------------------------------------------------------------

CREATE INDEX ix_absence_period_offer ON absence_period (offer_id, missing_since DESC);

CREATE INDEX ix_change_event_product ON change_event(source_product_id, change_event_id DESC);

CREATE INDEX ix_change_event_run ON change_event(run_id);

CREATE INDEX ix_change_event_time ON change_event(change_event_id DESC);

CREATE INDEX ix_classification_node_parent ON classification_node(parent_node_id);

CREATE INDEX ix_crawl_job_status ON crawl_job(status, created_at DESC);

CREATE INDEX ix_crawl_run_source_time ON crawl_run(source_id, started_at DESC);

CREATE INDEX ix_currency_rate_kind ON currency_rate(currency, source_kind, as_of DESC);

CREATE INDEX ix_currency_rate_latest ON currency_rate(currency, as_of DESC);

CREATE INDEX ix_dataset_definition_site
    ON dataset_definition(site_profile_id, dataset_definition_id, valid_to);

CREATE INDEX ix_dataset_field_order ON dataset_field(source_key, display_order);

CREATE INDEX ix_dataset_relationship_site
    ON dataset_relationship(site_profile_id, dataset_relationship_id, valid_to);

CREATE INDEX ix_feed_assignment_lookup
    ON feed_assignment(material_id, region) WHERE valid_to IS NULL;

CREATE INDEX ix_field_definition_dataset
    ON field_definition(dataset_definition_id, display_order, field_definition_id);

CREATE INDEX ix_field_definition_paging
    ON field_definition (dataset_definition_id, field_definition_id)
    WHERE valid_to IS NULL;

CREATE INDEX ix_generic_ingestion_dataset
    ON generic_ingestion(dataset_definition_id, generic_ingestion_id);

CREATE INDEX ix_generic_page_snapshot_hash
    ON generic_page_snapshot(content_hash, page_snapshot_id);

CREATE INDEX ix_generic_page_snapshot_page
    ON generic_page_snapshot(page_snapshot_id, captured_at);

CREATE INDEX ix_generic_record_page
    ON generic_record(dataset_definition_id, generic_record_id);

CREATE INDEX ix_generic_record_revision_record
    ON generic_record_revision(generic_record_id, record_revision_id);

CREATE INDEX ix_generic_record_snapshot
    ON generic_record(source_snapshot_id, generic_record_id);

CREATE INDEX ix_identity_alias_value
    ON identity_alias (alias_type, alias_value);

CREATE INDEX ix_job_log_job_time ON job_log_entry(job_id, job_log_id DESC);

CREATE INDEX ix_material_attr_current ON material_attribute_value(material_id, attribute_id) WHERE valid_to IS NULL;

CREATE INDEX ix_material_classification_current
    ON material_classification(material_id) WHERE valid_to IS NULL;

CREATE INDEX ix_material_gtin ON material(gtin) WHERE gtin IS NOT NULL;

CREATE INDEX ix_material_variant_material ON material_variant(material_id);

CREATE INDEX ix_price_obs_offer_pricehash
    ON price_observation (offer_id, observed_at DESC, price_hash);

CREATE INDEX ix_price_obs_offer_time ON price_observation(offer_id, observed_at DESC);

CREATE INDEX ix_price_obs_provenance
    ON price_observation (offer_id, provenance, business_date DESC,
                          price_observation_id DESC);

CREATE INDEX ix_price_period_offer ON price_period (offer_id, first_detected_at DESC);

CREATE INDEX ix_raw_snapshot_hash ON raw_snapshot(content_hash);

CREATE INDEX ix_relationship_field_pair_relationship
    ON relationship_field_pair(dataset_relationship_id, pair_order);

CREATE INDEX ix_retention_pin_offer ON retention_pin (offer_id);

CREATE INDEX ix_schedule_due ON schedule(enabled, next_run_at);

CREATE INDEX ix_schema_version_field_order
    ON schema_version_field(schema_version_id, field_order);

CREATE INDEX ix_site_profile_page ON site_profile(valid_to, site_profile_id);

CREATE INDEX ix_source_product_attribute_site_filter
    ON source_product_attribute (source_product_id, is_site_filter);

CREATE INDEX ix_source_product_curation ON source_product(source_id, curation);

CREATE INDEX ix_spa_product ON source_product_attribute(source_product_id);

CREATE INDEX ix_tax_rule_lookup
    ON tax_rule (source_key, region, material_key, valid_from DESC);

CREATE INDEX ix_variant_attr_current ON variant_attribute_value(variant_id, attribute_id) WHERE valid_to IS NULL;

CREATE UNIQUE INDEX ux_absence_period_open ON absence_period (offer_id)
    WHERE returned_at IS NULL;

CREATE UNIQUE INDEX ux_classification_mapping_active
    ON classification_mapping(source_node_id) WHERE valid_to IS NULL AND review_status = 'approved';

CREATE UNIQUE INDEX ux_classification_node_external
    ON classification_node(scheme_id, external_id) WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX ux_dataset_field ON dataset_field(source_key, field_key);

CREATE UNIQUE INDEX ux_dataset_schema_version_active
    ON dataset_schema_version(dataset_definition_id)
    WHERE valid_to IS NULL;

CREATE UNIQUE INDEX ux_feed_assignment_active
    ON feed_assignment(material_id, COALESCE(variant_id,0), region, priority)
    WHERE valid_to IS NULL;

CREATE UNIQUE INDEX ux_identity_alias
    ON identity_alias (source_product_id, alias_type, alias_value);

CREATE UNIQUE INDEX ux_material_variant_fingerprint
    ON material_variant(material_id, spec_fingerprint) WHERE spec_fingerprint IS NOT NULL;

CREATE UNIQUE INDEX ux_price_obs_dedupe ON price_observation(offer_id, business_date, record_hash);

CREATE UNIQUE INDEX ux_price_period_open
    ON price_period (offer_id) WHERE closed_at IS NULL;

CREATE UNIQUE INDEX ux_saved_view_name ON saved_view(source_key, view_name);

CREATE UNIQUE INDEX ux_source_offer_identity
    ON source_offer(source_variant_id, COALESCE(branch_id,''), country_code_alpha2, customer_segment,
                    COALESCE(selling_unit_id,0), basis_quantity);

CREATE UNIQUE INDEX ux_source_product_match_active
    ON source_product_match(source_product_id) WHERE valid_to IS NULL AND review_status = 'approved';

CREATE UNIQUE INDEX ux_source_variant_external
    ON source_variant(source_product_id, external_variant_id)
    WHERE external_variant_id IS NOT NULL;

CREATE UNIQUE INDEX ux_source_variant_fingerprint
    ON source_variant(source_product_id, option_fingerprint)
    WHERE external_variant_id IS NULL AND option_fingerprint IS NOT NULL;

CREATE UNIQUE INDEX ux_source_variant_match_active
    ON source_variant_match(source_variant_id) WHERE valid_to IS NULL AND review_status = 'approved';

CREATE UNIQUE INDEX ux_tax_rule_current
    ON tax_rule (source_key, region, material_key) WHERE valid_to IS NULL;

-- ---- triggers -----------------------------------------------------------

CREATE TRIGGER trg_dataset_relationship_same_site_insert
BEFORE INSERT ON dataset_relationship
FOR EACH ROW
WHEN (SELECT site_profile_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.parent_dataset_id LIMIT 1) <> NEW.site_profile_id
  OR (SELECT site_profile_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.child_dataset_id LIMIT 1) <> NEW.site_profile_id
BEGIN
    SELECT RAISE(ABORT, 'relationship datasets must belong to the same site profile');
END;

CREATE TRIGGER trg_dataset_relationship_same_site_update
BEFORE UPDATE OF site_profile_id, parent_dataset_id, child_dataset_id
ON dataset_relationship
FOR EACH ROW
WHEN (SELECT site_profile_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.parent_dataset_id LIMIT 1) <> NEW.site_profile_id
  OR (SELECT site_profile_id FROM dataset_definition
      WHERE dataset_definition_id = NEW.child_dataset_id LIMIT 1) <> NEW.site_profile_id
BEGIN
    SELECT RAISE(ABORT, 'relationship datasets must belong to the same site profile');
END;

CREATE TRIGGER trg_generic_ingestion_append_only_delete
BEFORE DELETE ON generic_ingestion
BEGIN
    SELECT RAISE(ABORT, 'generic ingestions are append-only');
END;

CREATE TRIGGER trg_generic_ingestion_append_only_update
BEFORE UPDATE ON generic_ingestion
BEGIN
    SELECT RAISE(ABORT, 'generic ingestions are append-only');
END;

CREATE TRIGGER trg_generic_ingestion_matches_insert
BEFORE INSERT ON generic_ingestion
FOR EACH ROW
WHEN NEW.dataset_definition_id <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'generic ingestion schema must belong to its dataset');
END;

CREATE TRIGGER trg_generic_page_snapshot_immutable_delete
BEFORE DELETE ON generic_page_snapshot
BEGIN
    SELECT RAISE(ABORT, 'saved HTML snapshots are immutable');
END;

CREATE TRIGGER trg_generic_page_snapshot_immutable_update
BEFORE UPDATE ON generic_page_snapshot
BEGIN
    SELECT RAISE(ABORT, 'saved HTML snapshots are immutable');
END;

CREATE TRIGGER trg_generic_record_revision_append_only_delete
BEFORE DELETE ON generic_record_revision
BEGIN
    SELECT RAISE(ABORT, 'generic record revisions are append-only');
END;

CREATE TRIGGER trg_generic_record_revision_append_only_update
BEFORE UPDATE ON generic_record_revision
BEGIN
    SELECT RAISE(ABORT, 'generic record revisions are append-only');
END;

CREATE TRIGGER trg_generic_record_revision_matches_insert
BEFORE INSERT ON generic_record_revision
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1) <>
     (SELECT dataset_definition_id FROM generic_record
      WHERE generic_record_id = NEW.generic_record_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'generic record revision schema must belong to its dataset');
END;

CREATE TRIGGER trg_generic_record_schema_matches_insert
BEFORE INSERT ON generic_record
FOR EACH ROW
WHEN NEW.dataset_definition_id <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'generic record schema must belong to its dataset');
END;

CREATE TRIGGER trg_generic_record_schema_matches_update
BEFORE UPDATE OF dataset_definition_id, schema_version_id ON generic_record
FOR EACH ROW
WHEN NEW.dataset_definition_id <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'generic record schema must belong to its dataset');
END;

CREATE TRIGGER trg_offer_unit_needs_a_witness_insert
BEFORE INSERT ON source_offer
WHEN NEW.selling_unit_id IS NOT NULL
 AND (NEW.unit_basis_provenance IS NULL OR NEW.unit_basis_provenance = ''
   OR NEW.unit_basis_witness IS NULL OR NEW.unit_basis_witness = '')
BEGIN
  SELECT RAISE(ABORT, 'a selling unit must carry its provenance and its witness');
END;

CREATE TRIGGER trg_offer_unit_needs_a_witness_update
BEFORE UPDATE OF selling_unit_id, unit_basis_provenance, unit_basis_witness ON source_offer
WHEN NEW.selling_unit_id IS NOT NULL
 AND (NEW.unit_basis_provenance IS NULL OR NEW.unit_basis_provenance = ''
   OR NEW.unit_basis_witness IS NULL OR NEW.unit_basis_witness = '')
BEGIN
  SELECT RAISE(ABORT, 'a selling unit must carry its provenance and its witness');
END;

CREATE TRIGGER trg_price_obs_no_delete
BEFORE DELETE ON price_observation
BEGIN
    SELECT RAISE(ABORT, 'price_observation is append-only (ENGINEERING.md A7)');
END;

CREATE TRIGGER trg_price_obs_no_update
BEFORE UPDATE ON price_observation
BEGIN
    SELECT RAISE(ABORT, 'price_observation is append-only (ENGINEERING.md A7)');
END;

CREATE TRIGGER trg_relationship_field_pair_matches_insert
BEFORE INSERT ON relationship_field_pair
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.parent_field_id LIMIT 1) <>
     (SELECT parent_dataset_id FROM dataset_relationship
      WHERE dataset_relationship_id = NEW.dataset_relationship_id LIMIT 1)
  OR (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.child_field_id LIMIT 1) <>
     (SELECT child_dataset_id FROM dataset_relationship
      WHERE dataset_relationship_id = NEW.dataset_relationship_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'relationship fields must belong to their mapped datasets');
END;

CREATE TRIGGER trg_relationship_field_pair_matches_update
BEFORE UPDATE OF dataset_relationship_id, parent_field_id, child_field_id
ON relationship_field_pair
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.parent_field_id LIMIT 1) <>
     (SELECT parent_dataset_id FROM dataset_relationship
      WHERE dataset_relationship_id = NEW.dataset_relationship_id LIMIT 1)
  OR (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.child_field_id LIMIT 1) <>
     (SELECT child_dataset_id FROM dataset_relationship
      WHERE dataset_relationship_id = NEW.dataset_relationship_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'relationship fields must belong to their mapped datasets');
END;

CREATE TRIGGER trg_schema_version_field_matches_insert
BEFORE INSERT ON schema_version_field
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.field_definition_id LIMIT 1) <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'schema fields must belong to the schema dataset');
END;

CREATE TRIGGER trg_schema_version_field_matches_update
BEFORE UPDATE OF schema_version_id, field_definition_id ON schema_version_field
FOR EACH ROW
WHEN (SELECT dataset_definition_id FROM field_definition
      WHERE field_definition_id = NEW.field_definition_id LIMIT 1) <>
     (SELECT dataset_definition_id FROM dataset_schema_version
      WHERE schema_version_id = NEW.schema_version_id LIMIT 1)
BEGIN
    SELECT RAISE(ABORT, 'schema fields must belong to the schema dataset');
END;

-- ---- identity --------------------------------------------------------------

INSERT INTO scrapex_meta (key, value) VALUES
    ('database_kind', 'engine'),
    ('migration_stream', 'engine');

-- The stream restarts at 1. Safe only while nothing is published and no
-- database in the world is stamped `engine`; from the first release on,
-- this number is as immovable as the price stream's is now.
PRAGMA user_version = 1;
