"""Typed SQLite boundaries for the engine database.

Each type owns a migration stream, application id, lock, health check, backup,
and restore path. Callers cannot accidentally pass one domain to the other.
"""
from __future__ import annotations

import hashlib
import os
import sqlite3
from collections.abc import Callable
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Generic, TypeVar

from .. import db as legacy_db
from ..database_ids import ENGINE_APPLICATION_ID, ENGINE_DATABASE_KIND

ROOT_DB_DIR = Path(__file__).resolve().parents[2] / "db"

# ONE FILE, AND ITS STREAM STARTS AGAIN AT 1. The whole warehouse — priced
# offers and generic records together — is v1, generated by
# tools/derive_engine_schema.py from the two streams it replaces. Everything
# after it is an ordinary numbered migration in the folder beside it.
#
# Restarting the numbering is safe here and would not be at any other moment:
# nothing is published, so no database in the world is stamped `engine` yet.
# The instant one is, this becomes as immovable as the price stream is now.
ENGINE_SCHEMA = ROOT_DB_DIR / "engine" / "schema.sql"
ENGINE_MIGRATIONS = ROOT_DB_DIR / "engine" / "migrations"

T = TypeVar("T")


class DatabaseUnavailableError(RuntimeError):
    """A requested operational database is missing or unreadable."""


class DatabaseKindError(RuntimeError):
    """A typed boundary was given the other domain's database."""


class MigrationStreamError(RuntimeError):
    """A migration stream no longer matches the shape its guards require.

    Raised by the plan builder, whose two checks exist because both
    failures renumber a database that has already shipped: a price migration
    renamed or deleted out from under the explicit legacy list, or one added
    below the identity boundary at v13. Both raise sites predate this class,
    so until now they raised NameError — the program still stopped, which is
    the important half, but it reported nothing about which migration moved.
    """


class DatabaseMigrationError(RuntimeError):
    """A migration stream is incomplete, newer, or has been edited in place."""


@dataclass(frozen=True)
class Migration:
    number: int
    path: Path

    @property
    def name(self) -> str:
        return self.path.name

    @property
    def sha256(self) -> str:
        """The migration's identity: its SQL, NOT its platform's newlines.

        Hashing raw bytes made this checksum platform-dependent, which turned
        the tamper guard into a false alarm. `.gitattributes` says `* text=auto`
        and core.autocrlf is on, so the repo stores LF and Windows checks out
        CRLF: the same committed migration hashes one way on the machine that
        stamped the ledger and another on the machine that reads it.

        It really fired. `general` migration 0003_field_paging_index.sql was
        stamped f57f56a4 (1,042 bytes, 23 LF) and read back ba24e532 (1,065
        bytes, 23 CRLF) — identical SQL — and refused every `scrapex ingest`
        and `backup-databases` on Windows. Measured across both live databases,
        57 of 57 migrations matched one form or the other and NOT ONE was
        genuinely edited: 41 had been stamped from LF content and 16 from CRLF.
        Re-stamping to CRLF would only have moved the failure to Linux and CI.

        Normalising costs no detection. A real edit changes the SQL, so both
        forms move and the guard still fails loudly; the only difference now
        accepted is a line ending, which never changes what the SQL does.
        """
        return hashlib.sha256(self._normalised_bytes()).hexdigest()

    @property
    def legacy_sha256(self) -> str:
        """The raw-bytes hash a pre-normalisation checkout stamped.

        Accepted on READ so an existing ledger keeps validating, and upgraded
        to `sha256` in place the next time the stream is stamped. Never used to
        accept an UNKNOWN digest: it matches only when this very file's raw
        bytes hash to the stored value, which proves the content is the same
        modulo newlines rather than assuming it.
        """
        return hashlib.sha256(self.path.read_bytes()).hexdigest()

    def _normalised_bytes(self) -> bytes:
        # CRLF and lone CR both fold to LF: the two conventions a Windows
        # checkout and an old Mac-style file can introduce.
        return self.path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")

    def matches(self, stored: str) -> bool:
        return stored in (self.sha256, self.legacy_sha256)


@dataclass(frozen=True)
class DatabaseHealth:
    kind: str
    path: str
    ok: bool
    status: str
    action: str
    schema_version: int | None
    application_id: int | None
    #: Whether the CORRUPTION scan ran. False on the panel's timed poll, which
    #: asks a different question and cannot afford this one — see `health`.
    #: Reported rather than implied, because "Healthy" would otherwise mean two
    #: different things depending on who asked.
    integrity_checked: bool = True

    def public(self) -> dict[str, Any]:
        return asdict(self)


def _utc_stamp() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ")


def _sqlite_connect(path: Path, *, create: bool) -> sqlite3.Connection:
    if not create and not path.is_file():
        raise DatabaseUnavailableError(
            f"database not found at {path}; reconnect its storage and try again"
        )
    if create:
        path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute("PRAGMA busy_timeout = 5000")
    return conn


def _folder_migrations(folder: Path, start: int = 2) -> list[Migration]:
    if not folder.is_dir():
        return []
    result: list[Migration] = []
    for path in sorted(folder.glob("[0-9][0-9][0-9][0-9]_*.sql")):
        number = int(path.name[:4])
        if number < start:
            continue
        result.append(Migration(number, path))
    return result


# `_MARKETLENS_LEGACY_NUMBERS` AND `_IDENTITY_POSITION` STOOD HERE AND ARE GONE
# (2026-08-30, OP-115). Both described a world with two migration streams in one
# directory: the tuple listed the price stream's numbers so the legacy facade
# could tell them apart, and it deliberately omitted 13 and 14 because those
# belonged to General.
#
# R-72 deleted that world — `db/` holds only `engine/`, and `db/general/` and
# `scrapex/databases/split.py` are gone — but the tuple survived it, and 13 and
# 14 had meanwhile become real engine migrations. `db.pending_migrations` was
# still filtering through it, so it could not report them AT ALL: measured on a
# database missing 0013, 0014 and 0016, it answered `[16]`.
#
# Recorded here rather than silently removed because the shape recurs: removing a
# duplicated system leaves behind the things that were SHAPED by it, and those
# are harder to find than the system was — nothing points at them any more.


class DomainDatabase(Generic[T]):
    """Base implementation; concrete domain types are the public capability."""

    kind: str
    application_id: int

    def __init__(self, path: Path | str, migrations: tuple[Migration, ...]):
        self.path = Path(path)
        self._migrations = migrations
        numbers = [item.number for item in migrations]
        if numbers != list(range(1, len(numbers) + 1)):
            raise DatabaseMigrationError(
                f"{self.kind} migrations must be gapless from 1, got {numbers}"
            )

    @property
    def latest_schema_version(self) -> int:
        return self._migrations[-1].number

    def initialize(self) -> list[int]:
        """Create or advance this database, then verify its physical identity."""
        with legacy_db.write_lock(self.path):
            existed = self.path.exists() and self.path.stat().st_size > 0
            conn = _sqlite_connect(self.path, create=True)
            try:
                if existed:
                    self._assert_not_other_kind(conn)
                applied = self._migrate(conn)
                self._verify(conn)
                return applied
            except Exception:
                conn.close()
                if not existed:
                    self._remove_new_database_files()
                raise
            finally:
                try:
                    conn.close()
                except sqlite3.Error:
                    pass

    def connect(self) -> sqlite3.Connection:
        conn = _sqlite_connect(self.path, create=False)
        try:
            self._verify(conn)
        except Exception:
            conn.close()
            raise
        return conn

    def write(self, action: Callable[[sqlite3.Connection], T]) -> T:
        with legacy_db.write_lock(self.path):
            conn = self.connect()
            try:
                result = action(conn)
                conn.commit()
                return result
            except Exception:
                conn.rollback()
                raise
            finally:
                conn.close()

    def health(self, *, integrity: bool = True) -> DatabaseHealth:
        """What is wrong with this database, if anything.

        `integrity=False` SKIPS THE CORRUPTION SCAN, and the reason is measured.
        `PRAGMA quick_check(1)` and `pragma_foreign_key_check` are O(FILE SIZE):
        on the owner's warehouse at 1,067 MB they cost **0.879 s and 0.398 s**,
        and `/api/health` calls this on every timed poll from the panel. At
        796 MB the whole endpoint fitted inside the extension's 2.5 s deadline
        (`extension/startup.js` `engineHealth`); after a merge took the file to
        1,067 MB it answered in **3.8 s** and the panel reported the engine as
        "Not detected" — while the engine was healthy and serving on 0.3.0.

        THE SPLIT IS A RULE THIS CODEBASE ALREADY STATES, not a new one:
        `storage.py:_warehouse_identity` says *"Integrity and identity are
        deliberately separate checks."* A timed poll asks identity — is it
        readable, at the version this build expects, and the right kind of file.
        Corruption is a different question, it does not develop between two polls
        seconds apart, and asking it on a timer costs a full file scan every few
        seconds for an answer nobody changed.

        `integrity_checked` rides on the result so the two answers are never
        confused: "Healthy" without a scan is a narrower claim than "Healthy"
        with one, and a caller that needs the wider one must ask for it.
        """
        if not self.path.is_file():
            return DatabaseHealth(
                self.kind, str(self.path), False, "Missing",
                "Reconnect the storage containing this database, then retry.",
                None, None, integrity_checked=integrity,
            )
        try:
            conn = self.connect()
            try:
                if integrity:
                    quick = conn.execute("PRAGMA quick_check(1)").fetchone()[0]
                    fk_problem = conn.execute(
                        "SELECT 1 FROM pragma_foreign_key_check LIMIT 1"
                    ).fetchone()
                else:
                    quick, fk_problem = "ok", None
                version = int(conn.execute("PRAGMA user_version").fetchone()[0])
                app_id = int(conn.execute("PRAGMA application_id").fetchone()[0])
            finally:
                conn.close()
            if quick != "ok" or fk_problem is not None:
                return DatabaseHealth(
                    self.kind, str(self.path), False, "Failed",
                    "Restore this database from a verified backup, then retry.",
                    version, app_id, integrity_checked=integrity,
                )
            return DatabaseHealth(
                self.kind, str(self.path), True, "Healthy",
                "No action is required.", version, app_id,
                integrity_checked=integrity,
            )
        except DatabaseMigrationError as exc:
            # A database whose schema does not match this build is unusable, but
            # it is not damaged. Reporting it as "Failed" and telling the owner to
            # restore a backup sends them to destroy good data over a one-command
            # upgrade, so this case gets its own status and its own instruction.
            version = self._schema_version_or_none()
            if version is not None and version > self.latest_schema_version:
                return DatabaseHealth(
                    self.kind, str(self.path), False, "Needs a newer ScrapeX",
                    f"This database was written by a later version (schema v{version}; "
                    f"this build reads v{self.latest_schema_version}). Update ScrapeX "
                    "and retry, and do not downgrade the database.",
                    version, None,
                )
            if version is not None and version == self.latest_schema_version:
                # NOT an upgrade. The schema is exactly the one this build reads,
                # so whatever raised had nothing to do with the version — in
                # practice it is a migration whose FILE changed after it was
                # applied, and _verify_checksums said so precisely. This branch
                # used to answer "at schema v51 and this build expects v51, run
                # init-db": a sentence that contradicts itself, naming a command
                # that raises the very same error, because `exc` was caught and
                # then dropped. The exception knew; the report threw it away.
                return DatabaseHealth(
                    self.kind, str(self.path), False, "Integrity check failed",
                    f"The schema version is correct (v{version}), so this is not an "
                    f"upgrade: {exc}",
                    version, None,
                )
            return DatabaseHealth(
                self.kind, str(self.path), False, "Needs upgrade",
                f"This database is at schema v{version} and this build expects "
                f"v{self.latest_schema_version}. Run 'python -m scrapex.cli init-db' "
                "to upgrade it, then retry.",
                version, None,
            )
        except (sqlite3.DatabaseError, DatabaseUnavailableError,
                DatabaseKindError) as exc:
            return DatabaseHealth(
                self.kind, str(self.path), False, "Failed",
                f"Choose the correct {self.kind} database or restore a verified backup, "
                f"then retry. ({exc})",
                None, None,
            )

    def _schema_version_or_none(self) -> int | None:
        """The stored schema version, read without the checks that just failed."""
        try:
            conn = sqlite3.connect(str(self.path))
            try:
                return int(conn.execute("PRAGMA user_version").fetchone()[0])
            finally:
                conn.close()
        except sqlite3.DatabaseError:
            return None

    def backup(self, folder: Path | str | None = None) -> Path:
        target_folder = Path(folder) if folder else self.path.parent / "backups"
        target_folder.mkdir(parents=True, exist_ok=True)
        target = target_folder / f"{self.path.stem}.{self.kind}-{_utc_stamp()}.db"
        incoming = target.with_suffix(".db.incoming")
        with legacy_db.write_lock(self.path):
            source = self.connect()
            destination = _sqlite_connect(incoming, create=True)
            try:
                source.backup(destination)
                destination.close()
                destination = None
                copied = self.__class__(incoming).connect()
                copied.close()
                os.replace(incoming, target)
            finally:
                source.close()
                if destination is not None:
                    destination.close()
                incoming.unlink(missing_ok=True)
        return target

    def restore(self, backup_path: Path | str) -> Path:
        backup = Path(backup_path)
        check = self.__class__(backup).connect()
        check.close()
        incoming = self.path.with_suffix(self.path.suffix + ".restore-incoming")
        displaced = self.path.with_name(
            f"{self.path.stem}.replaced-{_utc_stamp()}{self.path.suffix}"
        )
        with legacy_db.write_lock(self.path):
            try:
                source = self.__class__(backup).connect()
                try:
                    destination = _sqlite_connect(incoming, create=True)
                    try:
                        source.backup(destination)
                    finally:
                        destination.close()
                finally:
                    source.close()
                verified = self.__class__(incoming).connect()
                verified.close()
                try:
                    os.replace(self.path, displaced)
                    os.replace(incoming, self.path)
                except Exception:
                    if displaced.exists() and not self.path.exists():
                        os.replace(displaced, self.path)
                    raise
            finally:
                for suffix in ("", "-wal", "-shm"):
                    Path(str(incoming) + suffix).unlink(missing_ok=True)
        return displaced

    def _migrate(self, conn: sqlite3.Connection) -> list[int]:
        current = int(conn.execute("PRAGMA user_version").fetchone()[0])
        if current > self.latest_schema_version:
            raise DatabaseMigrationError(
                f"{self.kind} database schema v{current} is newer than this engine's "
                f"v{self.latest_schema_version}; upgrade ScrapeX and retry"
            )
        applied: list[int] = []
        for migration in self._migrations:
            if migration.number <= current:
                continue
            sql = migration.path.read_text(encoding="utf-8")
            # SQLite's documented table-rebuild procedure, done by the RUNNER
            # because a script cannot do it for itself: PRAGMA foreign_keys is
            # a silent no-op inside an open transaction, so a migration that
            # says OFF before dropping a parent table is not actually off in
            # here — migration 18 rolled back on every database that had job
            # history, while passing on every fresh test database that had
            # none. Enforcement is suspended around the script and the honest
            # compensator runs after: foreign_key_check over the whole file,
            # failing the migration loudly if it left a single orphan.
            # The runner must OWN the transaction, explicitly. In the sqlite3
            # module's legacy isolation mode the connection auto-commits an
            # open transaction before any non-DML statement — so the
            # foreign_key_check below would first COMMIT the very damage it
            # exists to veto. isolation_level None makes every BEGIN, COMMIT
            # and ROLLBACK ours and only ours.
            previous_isolation = conn.isolation_level
            conn.isolation_level = None
            conn.execute("PRAGMA foreign_keys = OFF")
            try:
                # No COMMIT is appended: the transaction stays open so the
                # check runs INSIDE it, and a failed check rolls the whole
                # migration back. Checked after commit it would only report
                # damage already made permanent. (No migration file carries
                # its own COMMIT; the runner owns it.)
                conn.executescript(f"BEGIN IMMEDIATE;\n{sql}")
                broken = conn.execute("PRAGMA foreign_key_check").fetchall()
                if broken:
                    raise DatabaseMigrationError(
                        f"{self.kind} migration {migration.name} left "
                        f"{len(broken)} row(s) pointing at nothing "
                        f"(first: {tuple(broken[0])}); it was applied with "
                        "enforcement suspended and must repair what it breaks")
                # The stream's version is corrected INSIDE the same
                # transaction. A file shared with the unified chain carries
                # THAT chain's number, and cannot also carry this stream's —
                # correcting it in a second commit (as this once did) left a
                # crash window where the file's higher number survived alone
                # and the next start misdiagnosed the database as written by
                # a NEWER ScrapeX. A file that set nothing at all is still a
                # mistake: the author forgot, and every later run would
                # replay it.
                stamped = int(conn.execute("PRAGMA user_version").fetchone()[0])
                if stamped == 0:
                    raise DatabaseMigrationError(
                        f"{self.kind} migration {migration.name} set no schema "
                        "version at all; add a PRAGMA user_version and retry")
                if stamped != migration.number:
                    conn.execute(f"PRAGMA user_version = {migration.number}")
                conn.execute("COMMIT")
            except Exception:
                if conn.in_transaction:
                    conn.execute("ROLLBACK")
                raise
            finally:
                conn.execute("PRAGMA foreign_keys = ON")
                conn.isolation_level = previous_isolation
            current = migration.number
            applied.append(current)
        self._stamp_and_verify_checksums(conn)
        return applied

    def _stamp_and_verify_checksums(self, conn: sqlite3.Connection) -> None:
        """Record each migration's digest, and refuse a file that changed under us.

        KEYED ON THE NAME, NOT THE NUMBER, and `OP-30` is why. `database_migration`
        is `migration_number INTEGER PRIMARY KEY` -- ONE number space -- and a
        warehouse that carried over from the price database holds TWO streams in it:
        this one at 1-5, and the price stream's fifty rows at 6-55. Engine migration
        `0006` was the first number this stream had ever wanted, and number 6 was
        already `0006_change_event.sql`, so the digests of two unrelated files were
        compared and the owner's live warehouse reported

            engine migration 0006_... checksum changed; restore the original
            migration file and retry

        while no file had changed at all. It could not be opened by any build.

        THE NAME IS UNIQUE ACROSS BOTH STREAMS, so a foreign row becomes invisible
        rather than fatal: this stream looks up only its own names, finds nothing for
        a name it has never stamped, and stamps it. The number stops carrying a
        meaning it had already lost -- with two streams sharing the space it never
        was "position in this stream" -- so a new row takes the next free one.

        WHY NOT A `stream` COLUMN, which is the model this deserves: that is a
        migration, and it would have to run BEFORE the verification that is failing.
        Recorded as the real fix in `OP-30`; this is the one that opens a warehouse
        today without a schema change, and it makes the collision impossible rather
        than deferred.

        NO TEST COULD HAVE CAUGHT THE ORIGINAL, and that is the part worth keeping: a
        fresh `init-db` writes only this stream's rows, so the space above 5 is empty
        and nothing collides. CI always starts from a fresh database. The collision
        needs a carried-over warehouse, and no fixture had one -- until the one beside
        this change.
        """
        for migration in self._migrations:
            stored = conn.execute(
                "SELECT sha256 FROM database_migration WHERE migration_name = ? LIMIT 1",
                (migration.name,),
            ).fetchone()
            if stored is not None and not migration.matches(stored[0]):
                raise DatabaseMigrationError(
                    f"{self.kind} migration {migration.name} checksum changed; restore "
                    "the original migration file and retry"
                )
            if stored is not None and stored[0] != migration.sha256:
                # A digest stamped from raw bytes, proven to be THIS file (see
                # Migration.legacy_sha256). Upgraded once, here in the path that
                # already owns the ledger, so the mixed state converges instead
                # of every reader having to know about both forms forever.
                conn.execute(
                    "UPDATE database_migration SET sha256 = ? WHERE migration_name = ?",
                    (migration.sha256, migration.name),
                )
            if stored is None:
                # THE NEXT FREE NUMBER, because this stream's own number may be held
                # by a foreign row. `migration_number` is the table's primary key and
                # stays one, so it still identifies a row -- it just stops pretending
                # to say where in this stream the row belongs.
                conn.execute(
                    "INSERT INTO database_migration "
                    "(migration_number, migration_name, sha256) VALUES "
                    "((SELECT COALESCE(MAX(migration_number), 0) + 1 "
                    "    FROM database_migration), ?, ?)",
                    (migration.name, migration.sha256),
                )
        conn.commit()

    def _assert_not_other_kind(self, conn: sqlite3.Connection) -> None:
        app_id = int(conn.execute("PRAGMA application_id").fetchone()[0])
        version = int(conn.execute("PRAGMA user_version").fetchone()[0])
        if app_id == 0 and version > 0:
            raise DatabaseKindError(
                f"{self.path} is an unmarked legacy database; run "
                "'scrapex split-databases' and retry"
            )
        if app_id not in (0, self.application_id):
            raise DatabaseKindError(
                f"expected a {self.kind} database at {self.path}, but its application id "
                f"is {app_id}; select the correct database and retry"
            )

    def _verify_checksums(self, conn: sqlite3.Connection) -> None:
        """The same lookup as the stamping path, and it has to be. `OP-30`: keyed on
        the number, this is what refused to open the owner's warehouse on every
        connection, not only on upgrade."""
        for migration in self._migrations:
            stored = conn.execute(
                "SELECT sha256 FROM database_migration WHERE migration_name = ? LIMIT 1",
                (migration.name,),
            ).fetchone()
            if stored is None:
                raise DatabaseMigrationError(
                    f"{self.kind} migration ledger is incomplete at {migration.name}; "
                    "run database initialization and retry"
                )
            if not migration.matches(stored[0]):
                raise DatabaseMigrationError(
                    f"{self.kind} migration {migration.name} checksum changed; restore "
                    "the original migration file and retry"
                )

    def _verify(self, conn: sqlite3.Connection) -> None:
        app_id = int(conn.execute("PRAGMA application_id").fetchone()[0])
        if app_id != self.application_id:
            raise DatabaseKindError(
                f"expected a {self.kind} database at {self.path}, but its application id "
                f"is {app_id}; select the correct database and retry"
            )
        try:
            row = conn.execute(
                "SELECT value FROM scrapex_meta WHERE key = 'database_kind' LIMIT 1"
            ).fetchone()
        except sqlite3.DatabaseError as exc:
            raise DatabaseKindError(
                f"{self.path} has no ScrapeX database marker; select the correct "
                f"{self.kind} database and retry"
            ) from exc
        if row is None or row[0] != self.kind:
            actual = row[0] if row else "unmarked"
            raise DatabaseKindError(
                f"expected database kind {self.kind!r}, found {actual!r}; select the "
                "correct database and retry"
            )
        current = int(conn.execute("PRAGMA user_version").fetchone()[0])
        if current != self.latest_schema_version:
            raise DatabaseMigrationError(
                f"{self.kind} database is at schema v{current}, expected "
                f"v{self.latest_schema_version}; run database initialization and retry"
            )
        self._verify_checksums(conn)

    def _remove_new_database_files(self) -> None:
        for suffix in ("", "-wal", "-shm"):
            Path(str(self.path) + suffix).unlink(missing_ok=True)


def _engine_plan() -> tuple[Migration, ...]:
    """One stream: the derived schema at v1, then the folder beside it."""
    return (Migration(1, ENGINE_SCHEMA), *_folder_migrations(ENGINE_MIGRATIONS))


class EngineDatabase(DomainDatabase[T]):
    """The whole warehouse, in one file, under the engine's own name.

    It carries what BOTH of the databases below carried — the priced offers and
    the generic records — because `db/engine/schema.sql` is derived from their
    two streams rather than written by hand. See tools/derive_engine_schema.py.

    It keeps the price database's two extra guarantees rather than starting
    without them, and that is the point of the collapse: the payload contract
    marker is stamped on migration and checked on verification, so a warehouse
    that has silently drifted from the contract the code speaks refuses to be
    used instead of returning quietly wrong rows.
    """

    kind = ENGINE_DATABASE_KIND
    application_id = ENGINE_APPLICATION_ID

    def __init__(self, path: Path | str):
        super().__init__(path, _engine_plan())

    def _migrate(self, conn: sqlite3.Connection) -> list[int]:
        applied = super()._migrate(conn)
        from ..contract import stamp_contract

        with conn:
            stamp_contract(conn)
        return applied

    def _verify(self, conn: sqlite3.Connection) -> None:
        super()._verify(conn)
        from ..contract import CONTRACT_VERSION, stored_contract_version

        stored = stored_contract_version(conn)
        if stored != CONTRACT_VERSION:
            raise DatabaseMigrationError(
                f"the engine database's contract marker is {stored!r}, expected "
                f"{CONTRACT_VERSION}; run 'scrapex init-db' or restore a "
                "compatible backup and retry"
            )


