"""Typed SQLite boundaries for General and MarketLens.

Each type owns a migration stream, application id, lock, health check, backup,
and restore path. Callers cannot accidentally pass one domain to the other.
"""
from __future__ import annotations

import hashlib
import os
import sqlite3
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Callable, Generic, TypeVar

from .. import db as legacy_db
from ..database_ids import ENGINE_APPLICATION_ID, ENGINE_DATABASE_KIND

ROOT_DB_DIR = Path(__file__).resolve().parents[2] / "db"

# ONE FILE, AND ITS STREAM STARTS AGAIN AT 1. The whole warehouse — priced
# offers and generic records together — is v1, generated by
# tools/derive_engine_schema.py from the two streams it replaces. Everything
# after it is an ordinary numbered migration in the folder beside it.
#
# Restarting the numbering is safe here and would not be at any other moment:
# nothing is published, so no database in the world is stamped `engine` yet.
# The instant one is, this becomes as immovable as the price stream is now.
ENGINE_SCHEMA = ROOT_DB_DIR / "engine" / "schema.sql"
ENGINE_MIGRATIONS = ROOT_DB_DIR / "engine" / "migrations"

T = TypeVar("T")


class DatabaseUnavailableError(RuntimeError):
    """A requested operational database is missing or unreadable."""


class DatabaseKindError(RuntimeError):
    """A typed boundary was given the other domain's database."""


class MigrationStreamError(RuntimeError):
    """A migration stream no longer matches the shape its guards require.

    Raised only by _marketlens_plan(), whose two checks exist because both
    failures renumber a database that has already shipped: a price migration
    renamed or deleted out from under the explicit legacy list, or one added
    below the identity boundary at v13. Both raise sites predate this class,
    so until now they raised NameError — the program still stopped, which is
    the important half, but it reported nothing about which migration moved.
    """


class DatabaseMigrationError(RuntimeError):
    """A migration stream is incomplete, newer, or has been edited in place."""


@dataclass(frozen=True)
class Migration:
    number: int
    path: Path

    @property
    def name(self) -> str:
        return self.path.name

    @property
    def sha256(self) -> str:
        """The migration's identity: its SQL, NOT its platform's newlines.

        Hashing raw bytes made this checksum platform-dependent, which turned
        the tamper guard into a false alarm. `.gitattributes` says `* text=auto`
        and core.autocrlf is on, so the repo stores LF and Windows checks out
        CRLF: the same committed migration hashes one way on the machine that
        stamped the ledger and another on the machine that reads it.

        It really fired. `general` migration 0003_field_paging_index.sql was
        stamped f57f56a4 (1,042 bytes, 23 LF) and read back ba24e532 (1,065
        bytes, 23 CRLF) — identical SQL — and refused every `scrapex ingest`
        and `backup-databases` on Windows. Measured across both live databases,
        57 of 57 migrations matched one form or the other and NOT ONE was
        genuinely edited: 41 had been stamped from LF content and 16 from CRLF.
        Re-stamping to CRLF would only have moved the failure to Linux and CI.

        Normalising costs no detection. A real edit changes the SQL, so both
        forms move and the guard still fails loudly; the only difference now
        accepted is a line ending, which never changes what the SQL does.
        """
        return hashlib.sha256(self._normalised_bytes()).hexdigest()

    @property
    def legacy_sha256(self) -> str:
        """The raw-bytes hash a pre-normalisation checkout stamped.

        Accepted on READ so an existing ledger keeps validating, and upgraded
        to `sha256` in place the next time the stream is stamped. Never used to
        accept an UNKNOWN digest: it matches only when this very file's raw
        bytes hash to the stored value, which proves the content is the same
        modulo newlines rather than assuming it.
        """
        return hashlib.sha256(self.path.read_bytes()).hexdigest()

    def _normalised_bytes(self) -> bytes:
        # CRLF and lone CR both fold to LF: the two conventions a Windows
        # checkout and an old Mac-style file can introduce.
        return self.path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")

    def matches(self, stored: str) -> bool:
        return stored in (self.sha256, self.legacy_sha256)


@dataclass(frozen=True)
class DatabaseHealth:
    kind: str
    path: str
    ok: bool
    status: str
    action: str
    schema_version: int | None
    application_id: int | None

    def public(self) -> dict[str, Any]:
        return asdict(self)


def _utc_stamp() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ")


def _sqlite_connect(path: Path, *, create: bool) -> sqlite3.Connection:
    if not create and not path.is_file():
        raise DatabaseUnavailableError(
            f"database not found at {path}; reconnect its storage and try again"
        )
    if create:
        path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute("PRAGMA busy_timeout = 5000")
    return conn


def _folder_migrations(folder: Path, start: int = 2) -> list[Migration]:
    if not folder.is_dir():
        return []
    result: list[Migration] = []
    for path in sorted(folder.glob("[0-9][0-9][0-9][0-9]_*.sql")):
        number = int(path.name[:4])
        if number < start:
            continue
        result.append(Migration(number, path))
    return result


# Legacy migrations belonging to the PRICE domain, in the order MarketLens
# applies them. Legacy 13 and 14 are deliberately absent — they created the
# generic catalogue and generic extraction storage, which are General's alone.
#
# Listed rather than ranged: the unified chain and this one have diverged, so a
# new price migration lands at the END of the legacy chain but in the middle of
# this plan. A range would silently swallow whatever General adds next.
_MARKETLENS_LEGACY_NUMBERS = (2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61)

# Where the identity migration sits in this stream. Everything before it is the
# price history the unified warehouse already had; everything after is a price
# migration written since the split.
_IDENTITY_POSITION = 13


class DomainDatabase(Generic[T]):
    """Base implementation; concrete domain types are the public capability."""

    kind: str
    application_id: int

    def __init__(self, path: Path | str, migrations: tuple[Migration, ...]):
        self.path = Path(path)
        self._migrations = migrations
        numbers = [item.number for item in migrations]
        if numbers != list(range(1, len(numbers) + 1)):
            raise DatabaseMigrationError(
                f"{self.kind} migrations must be gapless from 1, got {numbers}"
            )

    @property
    def latest_schema_version(self) -> int:
        return self._migrations[-1].number

    def initialize(self) -> list[int]:
        """Create or advance this database, then verify its physical identity."""
        with legacy_db.write_lock(self.path):
            existed = self.path.exists() and self.path.stat().st_size > 0
            conn = _sqlite_connect(self.path, create=True)
            try:
                if existed:
                    self._assert_not_other_kind(conn)
                applied = self._migrate(conn)
                self._verify(conn)
                return applied
            except Exception:
                conn.close()
                if not existed:
                    self._remove_new_database_files()
                raise
            finally:
                try:
                    conn.close()
                except sqlite3.Error:
                    pass

    def connect(self) -> sqlite3.Connection:
        conn = _sqlite_connect(self.path, create=False)
        try:
            self._verify(conn)
        except Exception:
            conn.close()
            raise
        return conn

    def write(self, action: Callable[[sqlite3.Connection], T]) -> T:
        with legacy_db.write_lock(self.path):
            conn = self.connect()
            try:
                result = action(conn)
                conn.commit()
                return result
            except Exception:
                conn.rollback()
                raise
            finally:
                conn.close()

    def health(self) -> DatabaseHealth:
        if not self.path.is_file():
            return DatabaseHealth(
                self.kind, str(self.path), False, "Missing",
                "Reconnect the storage containing this database, then retry.",
                None, None,
            )
        try:
            conn = self.connect()
            try:
                quick = conn.execute("PRAGMA quick_check(1)").fetchone()[0]
                fk_problem = conn.execute(
                    "SELECT 1 FROM pragma_foreign_key_check LIMIT 1"
                ).fetchone()
                version = int(conn.execute("PRAGMA user_version").fetchone()[0])
                app_id = int(conn.execute("PRAGMA application_id").fetchone()[0])
            finally:
                conn.close()
            if quick != "ok" or fk_problem is not None:
                return DatabaseHealth(
                    self.kind, str(self.path), False, "Failed",
                    "Restore this database from a verified backup, then retry.",
                    version, app_id,
                )
            return DatabaseHealth(
                self.kind, str(self.path), True, "Healthy",
                "No action is required.", version, app_id,
            )
        except DatabaseMigrationError as exc:
            # A database whose schema does not match this build is unusable, but
            # it is not damaged. Reporting it as "Failed" and telling the owner to
            # restore a backup sends them to destroy good data over a one-command
            # upgrade, so this case gets its own status and its own instruction.
            version = self._schema_version_or_none()
            if version is not None and version > self.latest_schema_version:
                return DatabaseHealth(
                    self.kind, str(self.path), False, "Needs a newer ScrapeX",
                    f"This database was written by a later version (schema v{version}; "
                    f"this build reads v{self.latest_schema_version}). Update ScrapeX "
                    "and retry, and do not downgrade the database.",
                    version, None,
                )
            if version is not None and version == self.latest_schema_version:
                # NOT an upgrade. The schema is exactly the one this build reads,
                # so whatever raised had nothing to do with the version — in
                # practice it is a migration whose FILE changed after it was
                # applied, and _verify_checksums said so precisely. This branch
                # used to answer "at schema v51 and this build expects v51, run
                # init-db": a sentence that contradicts itself, naming a command
                # that raises the very same error, because `exc` was caught and
                # then dropped. The exception knew; the report threw it away.
                return DatabaseHealth(
                    self.kind, str(self.path), False, "Integrity check failed",
                    f"The schema version is correct (v{version}), so this is not an "
                    f"upgrade: {exc}",
                    version, None,
                )
            return DatabaseHealth(
                self.kind, str(self.path), False, "Needs upgrade",
                f"This database is at schema v{version} and this build expects "
                f"v{self.latest_schema_version}. Run 'python -m scrapex.cli init-db' "
                "to upgrade it, then retry.",
                version, None,
            )
        except (sqlite3.DatabaseError, DatabaseUnavailableError,
                DatabaseKindError) as exc:
            return DatabaseHealth(
                self.kind, str(self.path), False, "Failed",
                f"Choose the correct {self.kind} database or restore a verified backup, "
                f"then retry. ({exc})",
                None, None,
            )

    def _schema_version_or_none(self) -> int | None:
        """The stored schema version, read without the checks that just failed."""
        try:
            conn = sqlite3.connect(str(self.path))
            try:
                return int(conn.execute("PRAGMA user_version").fetchone()[0])
            finally:
                conn.close()
        except sqlite3.DatabaseError:
            return None

    def backup(self, folder: Path | str | None = None) -> Path:
        target_folder = Path(folder) if folder else self.path.parent / "backups"
        target_folder.mkdir(parents=True, exist_ok=True)
        target = target_folder / f"{self.path.stem}.{self.kind}-{_utc_stamp()}.db"
        incoming = target.with_suffix(".db.incoming")
        with legacy_db.write_lock(self.path):
            source = self.connect()
            destination = _sqlite_connect(incoming, create=True)
            try:
                source.backup(destination)
                destination.close()
                destination = None
                copied = self.__class__(incoming).connect()
                copied.close()
                os.replace(incoming, target)
            finally:
                source.close()
                if destination is not None:
                    destination.close()
                incoming.unlink(missing_ok=True)
        return target

    def restore(self, backup_path: Path | str) -> Path:
        backup = Path(backup_path)
        check = self.__class__(backup).connect()
        check.close()
        incoming = self.path.with_suffix(self.path.suffix + ".restore-incoming")
        displaced = self.path.with_name(
            f"{self.path.stem}.replaced-{_utc_stamp()}{self.path.suffix}"
        )
        with legacy_db.write_lock(self.path):
            try:
                source = self.__class__(backup).connect()
                try:
                    destination = _sqlite_connect(incoming, create=True)
                    try:
                        source.backup(destination)
                    finally:
                        destination.close()
                finally:
                    source.close()
                verified = self.__class__(incoming).connect()
                verified.close()
                try:
                    os.replace(self.path, displaced)
                    os.replace(incoming, self.path)
                except Exception:
                    if displaced.exists() and not self.path.exists():
                        os.replace(displaced, self.path)
                    raise
            finally:
                for suffix in ("", "-wal", "-shm"):
                    Path(str(incoming) + suffix).unlink(missing_ok=True)
        return displaced

    def _migrate(self, conn: sqlite3.Connection) -> list[int]:
        current = int(conn.execute("PRAGMA user_version").fetchone()[0])
        if current > self.latest_schema_version:
            raise DatabaseMigrationError(
                f"{self.kind} database schema v{current} is newer than this engine's "
                f"v{self.latest_schema_version}; upgrade ScrapeX and retry"
            )
        applied: list[int] = []
        for migration in self._migrations:
            if migration.number <= current:
                continue
            sql = migration.path.read_text(encoding="utf-8")
            # SQLite's documented table-rebuild procedure, done by the RUNNER
            # because a script cannot do it for itself: PRAGMA foreign_keys is
            # a silent no-op inside an open transaction, so a migration that
            # says OFF before dropping a parent table is not actually off in
            # here — migration 18 rolled back on every database that had job
            # history, while passing on every fresh test database that had
            # none. Enforcement is suspended around the script and the honest
            # compensator runs after: foreign_key_check over the whole file,
            # failing the migration loudly if it left a single orphan.
            # The runner must OWN the transaction, explicitly. In the sqlite3
            # module's legacy isolation mode the connection auto-commits an
            # open transaction before any non-DML statement — so the
            # foreign_key_check below would first COMMIT the very damage it
            # exists to veto. isolation_level None makes every BEGIN, COMMIT
            # and ROLLBACK ours and only ours.
            previous_isolation = conn.isolation_level
            conn.isolation_level = None
            conn.execute("PRAGMA foreign_keys = OFF")
            try:
                # No COMMIT is appended: the transaction stays open so the
                # check runs INSIDE it, and a failed check rolls the whole
                # migration back. Checked after commit it would only report
                # damage already made permanent. (No migration file carries
                # its own COMMIT; the runner owns it.)
                conn.executescript(f"BEGIN IMMEDIATE;\n{sql}")
                broken = conn.execute("PRAGMA foreign_key_check").fetchall()
                if broken:
                    raise DatabaseMigrationError(
                        f"{self.kind} migration {migration.name} left "
                        f"{len(broken)} row(s) pointing at nothing "
                        f"(first: {tuple(broken[0])}); it was applied with "
                        "enforcement suspended and must repair what it breaks")
                # The stream's version is corrected INSIDE the same
                # transaction. A file shared with the unified chain carries
                # THAT chain's number, and cannot also carry this stream's —
                # correcting it in a second commit (as this once did) left a
                # crash window where the file's higher number survived alone
                # and the next start misdiagnosed the database as written by
                # a NEWER ScrapeX. A file that set nothing at all is still a
                # mistake: the author forgot, and every later run would
                # replay it.
                stamped = int(conn.execute("PRAGMA user_version").fetchone()[0])
                if stamped == 0:
                    raise DatabaseMigrationError(
                        f"{self.kind} migration {migration.name} set no schema "
                        "version at all; add a PRAGMA user_version and retry")
                if stamped != migration.number:
                    conn.execute(f"PRAGMA user_version = {migration.number}")
                conn.execute("COMMIT")
            except Exception:
                if conn.in_transaction:
                    conn.execute("ROLLBACK")
                raise
            finally:
                conn.execute("PRAGMA foreign_keys = ON")
                conn.isolation_level = previous_isolation
            current = migration.number
            applied.append(current)
        self._stamp_and_verify_checksums(conn)
        return applied

    def _stamp_and_verify_checksums(self, conn: sqlite3.Connection) -> None:
        for migration in self._migrations:
            stored = conn.execute(
                "SELECT sha256 FROM database_migration WHERE migration_number = ? LIMIT 1",
                (migration.number,),
            ).fetchone()
            if stored is not None and not migration.matches(stored[0]):
                raise DatabaseMigrationError(
                    f"{self.kind} migration {migration.name} checksum changed; restore "
                    "the original migration file and retry"
                )
            if stored is not None and stored[0] != migration.sha256:
                # A digest stamped from raw bytes, proven to be THIS file (see
                # Migration.legacy_sha256). Upgraded once, here in the path that
                # already owns the ledger, so the mixed state converges instead
                # of every reader having to know about both forms forever.
                conn.execute(
                    "UPDATE database_migration SET sha256 = ? WHERE migration_number = ?",
                    (migration.sha256, migration.number),
                )
            if stored is None:
                conn.execute(
                    "INSERT INTO database_migration "
                    "(migration_number, migration_name, sha256) VALUES (?,?,?)",
                    (migration.number, migration.name, migration.sha256),
                )
        conn.commit()

    def _assert_not_other_kind(self, conn: sqlite3.Connection) -> None:
        app_id = int(conn.execute("PRAGMA application_id").fetchone()[0])
        version = int(conn.execute("PRAGMA user_version").fetchone()[0])
        if app_id == 0 and version > 0:
            raise DatabaseKindError(
                f"{self.path} is an unmarked legacy database; run "
                "'scrapex split-databases' and retry"
            )
        if app_id not in (0, self.application_id):
            raise DatabaseKindError(
                f"expected a {self.kind} database at {self.path}, but its application id "
                f"is {app_id}; select the correct database and retry"
            )

    def _verify_checksums(self, conn: sqlite3.Connection) -> None:
        for migration in self._migrations:
            stored = conn.execute(
                "SELECT sha256 FROM database_migration WHERE migration_number = ? LIMIT 1",
                (migration.number,),
            ).fetchone()
            if stored is None:
                raise DatabaseMigrationError(
                    f"{self.kind} migration ledger is incomplete at {migration.name}; "
                    "run database initialization and retry"
                )
            if not migration.matches(stored[0]):
                raise DatabaseMigrationError(
                    f"{self.kind} migration {migration.name} checksum changed; restore "
                    "the original migration file and retry"
                )

    def _verify(self, conn: sqlite3.Connection) -> None:
        app_id = int(conn.execute("PRAGMA application_id").fetchone()[0])
        if app_id != self.application_id:
            raise DatabaseKindError(
                f"expected a {self.kind} database at {self.path}, but its application id "
                f"is {app_id}; select the correct database and retry"
            )
        try:
            row = conn.execute(
                "SELECT value FROM scrapex_meta WHERE key = 'database_kind' LIMIT 1"
            ).fetchone()
        except sqlite3.DatabaseError as exc:
            raise DatabaseKindError(
                f"{self.path} has no ScrapeX database marker; select the correct "
                f"{self.kind} database and retry"
            ) from exc
        if row is None or row[0] != self.kind:
            actual = row[0] if row else "unmarked"
            raise DatabaseKindError(
                f"expected database kind {self.kind!r}, found {actual!r}; select the "
                "correct database and retry"
            )
        current = int(conn.execute("PRAGMA user_version").fetchone()[0])
        if current != self.latest_schema_version:
            raise DatabaseMigrationError(
                f"{self.kind} database is at schema v{current}, expected "
                f"v{self.latest_schema_version}; run database initialization and retry"
            )
        self._verify_checksums(conn)

    def _remove_new_database_files(self) -> None:
        for suffix in ("", "-wal", "-shm"):
            Path(str(self.path) + suffix).unlink(missing_ok=True)


def _engine_plan() -> tuple[Migration, ...]:
    """One stream: the derived schema at v1, then the folder beside it."""
    return tuple([Migration(1, ENGINE_SCHEMA), *_folder_migrations(ENGINE_MIGRATIONS)])


class EngineDatabase(DomainDatabase[T]):
    """The whole warehouse, in one file, under the engine's own name.

    It carries what BOTH of the databases below carried — the priced offers and
    the generic records — because `db/engine/schema.sql` is derived from their
    two streams rather than written by hand. See tools/derive_engine_schema.py.

    It keeps the price database's two extra guarantees rather than starting
    without them, and that is the point of the collapse: the payload contract
    marker is stamped on migration and checked on verification, so a warehouse
    that has silently drifted from the contract the code speaks refuses to be
    used instead of returning quietly wrong rows.
    """

    kind = ENGINE_DATABASE_KIND
    application_id = ENGINE_APPLICATION_ID

    def __init__(self, path: Path | str):
        super().__init__(path, _engine_plan())

    def _migrate(self, conn: sqlite3.Connection) -> list[int]:
        applied = super()._migrate(conn)
        from ..contract import stamp_contract

        with conn:
            stamp_contract(conn)
        return applied

    def _verify(self, conn: sqlite3.Connection) -> None:
        super()._verify(conn)
        from ..contract import CONTRACT_VERSION, stored_contract_version

        stored = stored_contract_version(conn)
        if stored != CONTRACT_VERSION:
            raise DatabaseMigrationError(
                f"the engine database's contract marker is {stored!r}, expected "
                f"{CONTRACT_VERSION}; run 'scrapex init-db' or restore a "
                "compatible backup and retry"
            )


