"""Report class names a stylesheet defines that nothing anywhere else mentions.

A class deleted while a code path still builds it is an invisible regression —
the same failure as an undefined class, in the other direction — so the test
here is deliberately crude and deliberately conservative:

    a class is a CANDIDATE only if its name appears nowhere in the repository
    outside stylesheets. Not in markup, not in a template expression, not in
    JavaScript, not in Python, not in a test.

That misses classes built by string concatenation (`"tone-" + kind`), which is
why this prints a REPORT and is not a gate. Deleting anything it names still
needs a human to look, and tools/style_snapshot.py to prove the pages did not
move.

    python tools/dead_css.py
    python tools/dead_css.py --sheet extension/app.css
"""
from __future__ import annotations

import argparse
import collections
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: Everything that could mention a class name. Stylesheets are excluded — a
#: name used only by other CSS is still only used by CSS.
SEARCHED = (".html", ".js", ".mjs", ".py", ".json", ".md", ".yaml", ".yml")
SKIP_DIRS = {".git", "node_modules", ".claude", "__pycache__", ".pytest_cache",
             "vendor", "htmlcov", "dist", "build"}

#: Names nothing in this repository writes, and that are still very much alive
#: because something else writes them at runtime. Twenty of the twenty-eight
#: candidates on the first run were these — the report is nearly all noise
#: without them, and a reader who deletes one breaks a page that every test
#: still passes on.
RUNTIME = (
    (re.compile(r"^tabulator-"),
     "generated by the Tabulator grid library at runtime; the theme styles what "
     "the library builds and nothing here ever writes the name"),
    (re.compile(r"^schedule-state-"),
     "built by the template as `schedule-state-{{ state }}`, so the whole name "
     "never appears anywhere as text"),
)


def _runtime_reason(name: str) -> str | None:
    for pattern, reason in RUNTIME:
        if pattern.match(name):
            return reason
    return None


def _sheets() -> list[Path]:
    out = [ROOT / "design/components.css", ROOT / "extension/app.css",
           ROOT / "extension/onboarding.css"]
    out += [p for p in sorted((ROOT / "scrapex/webui/static").rglob("*.css"))
            if p.name not in ("components.css", "tokens.css") and "vendor" not in p.parts]
    return [p for p in out if p.exists()]


def _defined(css: str) -> set[str]:
    body = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    body = re.sub(r"url\([^)]*\)", "", body)
    return set(re.findall(r"\.([a-zA-Z][\w-]*)", body))


def _mentioned() -> set[str]:
    """Every word-like token in every non-stylesheet file, as one set.

    Crude on purpose. A name that appears inside a sentence in a comment counts
    as mentioned, and that is the correct bias: the cost of keeping a dead rule
    is a few bytes, and the cost of deleting a live one is a broken page.
    """
    words: set[str] = set()
    token = re.compile(r"[A-Za-z][\w-]*")
    for path in ROOT.rglob("*"):
        if path.suffix not in SEARCHED or not path.is_file():
            continue
        if SKIP_DIRS & set(path.parts):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        words.update(token.findall(text))
    return words


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sheet", help="report one stylesheet only")
    args = parser.parse_args()

    mentioned = _mentioned()
    per_sheet: dict[str, list[str]] = collections.OrderedDict()
    explained: collections.Counter = collections.Counter()
    total_defined = 0
    for sheet in _sheets():
        relative = str(sheet.relative_to(ROOT)).replace("\\", "/")
        if args.sheet and args.sheet not in relative:
            continue
        defined = _defined(sheet.read_text(encoding="utf-8"))
        total_defined += len(defined)
        unmentioned = sorted(defined - mentioned)
        keep = []
        for name in unmentioned:
            reason = _runtime_reason(name)
            if reason:
                explained[reason] += 1
            else:
                keep.append(name)
        per_sheet[relative] = keep

    candidates = sum(len(v) for v in per_sheet.values())
    print(f"{total_defined} class names defined - {candidates} candidates "
          f"({sum(explained.values())} written at runtime, listed below)\n")
    for relative, names in per_sheet.items():
        if not names:
            continue
        print(f"  {len(names):>3}  {relative}")
        for name in names:
            print(f"         {name}")
    if explained:
        print("\nWritten at runtime, therefore NOT candidates:")
        for reason, count in explained.most_common():
            print(f"  {count:>3}  {reason}")
    print("\nA candidate is not a verdict. Read each rule, then prove the pages "
          "did not move:\n  python tools/style_snapshot.py before.json"
          "\n  ...delete...\n  python tools/style_snapshot.py after.json"
          "\n  python tools/style_snapshot.py --diff before.json after.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
