"""Write db/engine/schema.sql from the two streams it replaces.

M5 collapses General and MarketLens into one database. The owner's own data does
not have to survive it — nothing is published, so no user can be hurt — and
"build it from scratch" is therefore the cheap and correct instruction.

BUT "FROM SCRATCH" APPLIES TO THE DATA, NOT TO THE SCHEMA. Sixty-two migrations
sit behind the shape those two databases have now: a column order that says who
arranged it, an offer that can be superseded, a run that says whether it had
warnings, and fifty-nine more. Retyping that by hand would drop some of it in
silence — a table nobody notices is missing until a report comes back empty, or
a trigger whose absence turns an append-only log into an editable one.

So the schema is DERIVED. This applies both streams to throwaway databases, and
writes their union. The machine carries sixty-two files' meaning across; a hand
does not. tests/test_one_schema_carries_both_streams.py then re-derives and
compares, so the committed file cannot drift from the streams it claims to be.

    python tools/derive_engine_schema.py            # write it
    python tools/derive_engine_schema.py --check    # fail if it would change

The union is safe to take because the two streams barely touch: exactly three
objects are defined in both — `database_migration`, `scrapex_meta` and the
autoindex under it — and all three are byte-identical. Anything else appearing
in both would be a real collision and this refuses rather than picking a winner.
"""
from __future__ import annotations

import argparse
import pathlib
import sqlite3
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "db" / "engine" / "schema.sql"

#: Tables before the things that reference them. SQLite does not enforce a
#: foreign key at CREATE time, so tables need no order among themselves, but a
#: trigger or an index naming a table that does not exist yet is an error.
ORDER = ("table", "view", "index", "trigger")


def _objects(db) -> dict[tuple[str, str], str]:
    """Every schema object a built database carries, keyed by (type, name).

    Rows whose `sql` is NULL are skipped: those are the indexes SQLite creates
    for itself under a PRIMARY KEY or UNIQUE, and writing them out by hand would
    be both wrong and rejected.
    """
    with tempfile.TemporaryDirectory() as tmp:
        path = pathlib.Path(tmp) / "derive.db"
        db(path).initialize()
        con = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
        try:
            return {(typ, name): sql for typ, name, sql in con.execute(
                "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL")}
        finally:
            con.close()


def derive() -> str:
    from scrapex.databases.domain import GeneralDatabase, MarketLensDatabase

    price = _objects(MarketLensDatabase)
    generic = _objects(GeneralDatabase)

    # A name in both streams meaning two different things cannot be merged, and
    # guessing which one wins is how a schema silently loses a constraint.
    clashes = sorted(key for key in set(price) & set(generic)
                     if price[key].strip() != generic[key].strip())
    if clashes:
        raise SystemExit(
            "these objects are defined differently in the two streams and "
            f"cannot be merged automatically: {clashes}")

    merged = {**price, **generic}
    lines = [
        "-- ScrapeX-Engine, one database, one schema.",
        "--",
        "-- GENERATED by tools/derive_engine_schema.py from the two streams this",
        "-- replaces: the price stream (MarketLens) and the generic stream",
        "-- (General). Do not hand-edit — tests/test_one_schema_carries_both_"
        "streams.py",
        "-- re-derives this and fails on any difference.",
        "--",
        f"-- {len([k for k in merged if k[0] == 'table'])} tables, "
        f"{len([k for k in merged if k[0] == 'index'])} indexes, "
        f"{len([k for k in merged if k[0] == 'trigger'])} triggers, "
        f"{len([k for k in merged if k[0] == 'view'])} views.",
        "",
    ]
    for kind in ORDER:
        names = sorted(name for typ, name in merged if typ == kind)
        if not names:
            continue
        lines.append(f"-- ---- {kind}s " + "-" * (66 - len(kind)))
        lines.append("")
        for name in names:
            lines.append(merged[(kind, name)].strip().rstrip(";") + ";")
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file is not what would be written")
    args = ap.parse_args()

    text = derive()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is not what the streams derive to; "
                  "run tools/derive_engine_schema.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} matches the streams")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
